### ISSUE TITLE
Issue with IsPlayerInGangZone(...);

### ISSUE THREAD

**Issue by stamenkovicc** [openmultiplayer/open.mp#1000]
`IsPlayerInGangZone(...);` cannot be used without calling `UseGangZoneCheck(..., true);` first. This requirement is unnecessary or should at least be documented on the [Open.MP documentation page](https://www.open.mp/docs/scripting/functions/IsPlayerInGangZone) to inform users.

**Comment by NexiusTailer** [comment]
Should be probably addressed to the [openmultiplayer/web](https://github.com/openmultiplayer/web) repo
