### ISSUE TITLE
GetTime raknet

### ISSUE THREAD

**Issue by plakapenka** [openmultiplayer/open.mp#1006]
check out this github, everything is described there https://github.com/vsergeenko777/samp-plugin-raktimefix

omp (your version of raknet) also includes this bug

**Comment by AmyrAhmady** [comment]
Why do you say it exists in omp? We already fixed it in 2021/2022

**Comment by plakapenka** [comment]
lol, I don't know where I was looking, I confused it with initialTime or something.
Sorry
