### ISSUE TITLE
SetPlayerScore in OnPlayerDisconnect

### ISSUE THREAD

**Issue by Raphinity** [openmultiplayer/open.mp#1010]
**Describe the bug**
A player having a score (SetPlayerScore) who disconnects, remains in the players list (on client) when SetPlayerScore is used in OnPlayerDisconnect.

**To Reproduce**
It happens on our open.mp server.
It hasn't been tested on a "blank" gamemode, therefore it needs to be reproduced.
1. Set a Score to a connected player --> ` SetPlayerScore(playerid,48);`
2. Change his score in OnPlayerDisconnect --> ` SetPlayerScore(playerid,0);` 
3. The player remains in the players list, whereas he is disconnected.

**Expected behavior**
If it's confirmed, it may be abused to get a full list of ghost players.

**Release version**
v1.3.1.2748 [Latest]

**Comment by AmyrAhmady** [comment]
Already fixed in nightly builds
https://github.com/openmultiplayer/open.mp/actions/workflows/build.yml?query=branch%3Amaster+event%3Apush
