### ISSUE TITLE
AddSimpleModel - Collision File

### ISSUE THREAD

**Issue by stamenkovicc** [openmultiplayer/open.mp#1012]
## [Collision - en.wikipedia.org](https://en.wikipedia.org/wiki/Collision)
I would like to propose changes to "AddSimpleModel" by adding one more parameter for the collision file.

```pawn
AddSimpleModel(virtualWorld, baseid, newid, const dff[], const textureLibrary[], const collisionFile[] = "");
```

[AddSimpleModel - Open.MP documentation page](https://www.open.mp/docs/scripting/functions/AddSimpleModel)

**Comment by spicybung** [comment]
Why do this? This isn't how collisions work in SA-MP. SAMP collision is baked into the .DFF opposed to being loaded from a library. What you propose means the client loading .COL files too not just .TXD and .DFF files - which adds bloat, and more.  There's a lot wrong with this.

**Comment by eakwarp** [comment]
> ## [Collision - en.wikipedia.org](https://en.wikipedia.org/wiki/Collision)
> I would like to propose changes to "AddSimpleModel" by adding one more parameter for the collision file.
> 
> ```pawn
> AddSimpleModel(virtualWorld, baseid, newid, const dff[], const textureLibrary[], const collisionFile[] = "");
> ```
> 
> [AddSimpleModel - Open.MP documentation page](https://www.open.mp/docs/scripting/functions/AddSimpleModel)

use kdff gui by samp team
https://sampforum.blast.hk/showthread.php?tid=644075
https://github.com/openmultiplayer/archive/blob/master/tools/kdffgui_025b_feb2019.zip
