### ISSUE TITLE
Label not showing near object

### ISSUE THREAD

**Issue by Trysha-rbrn** [openmultiplayer/open.mp#1022]
When you try to create a label near the object 19526, it won't show unless it is at least ~2.5 units away from the object. I have verified that the label is indeed created, but it is not displayed.

Initially, I thought the issue was related to the virtual world or the interior's ID, but that doesn't seem to be the case (since the object is always displayed, but the label is not).

```
CreateATM(i)
{
	AtmInfo[i][aAtmLabel] = CreateDynamic3DTextLabel(va_return(""SRWBOJA"> {FFFFFF}BANKOMAT - "SRWBOJA"%d <\n\n"SRWBOJA"'LALT'", i), 
		-1, AtmInfo[i][aX], AtmInfo[i][aY], AtmInfo[i][aZ]+2.5, 15.0, .worldid=AtmInfo[i][aVW], .interiorid=AtmInfo[i][aInt],.testlos = 1);

	AtmInfo[i][aObjekat] = CreateDynamicObject(ATM_OBJEKAT, AtmInfo[i][aX], AtmInfo[i][aY], AtmInfo[i][aZ], 0.0, 0.0, AtmInfo[i][aAngle], AtmInfo[i][aVW], AtmInfo[i][aInt],_,_);
	return 1;
}
```

EDIT: I just found out that the label is not being created in the same position as the object (this applies to every object). So, I'm going to close this issue because I initially thought it was a problem with only one type of object.

**Comment by ReshiramZekrom1** [comment]
Did you try to set false to testlos?

**Comment by Vince0789** [comment]
Please provide a minimum, complete and verifiable example. That is, with literal coordinates and without using any third party plugins.
