### ISSUE TITLE
Server Closed Connection

### ISSUE THREAD

**Issue by najuaircrack** [openmultiplayer/open.mp#1023]
Title: Server randomly closing connections immediately after "Connected to IP:Port"

---

Description:
Sometimes, when a player connects to the server, they see the message `Connected to IP:Port`, but almost immediately after, they receive `Server Closed Connection`. The issue happens sporadically and doesn't seem to follow a predictable pattern.

The key points are:
- The server logs do not record any connection or disconnection events for the affected player.
- There are no logs indicating that the player was kicked or banned.
- This makes the issue hard to debug or reproduce consistently.

---

Steps to Reproduce:
1. Start the server using **[your SA-MP/OpenMP version]**.
2. Attempt to connect as a player from a client.
3. Observe that sometimes the connection closes immediately with no logs or kick/ban evidence.
4. The exact conditions for reproduction are unclear. This happens sporadically.

---

Expected Behavior:
Players should successfully connect to the server without the connection being closed immediately unless explicitly kicked, banned, or due to some other server-side logic.

---

Observed Behavior:
- Server closes the connection immediately after showing `Connected to IP:Port`.
- No logs are generated on the server side about the connection attempt or disconnection reason.

---

Server Configuration and Environment:
- **Server version:** [openmp latest]
- **Operating system:** [Linux]
- **Plugins:** 
   "legacy_plugins": 
            "crashdetect.so",
            "whirlpool.so",
            "sscanf.so",
            "GPS.so",
            "streamer.so",
            "mysql_static.so",
            "profiler.so",
            "textdraw-streamer.so",
            "PawnPlus.so"
- **Filterscripts:** 
  [sampvoice]
- **Gamemode:** 
  [AKRPV6]
- **Network conditions:** 
  [Good]

---

Troubleshooting Steps Taken:
1. Checked the server logs for any connection or disconnection entries—none were found.
2. Verified that no bans or kicks were being triggered via server-side scripts or filterscripts.
3. Tested the server with minimal configuration (disabling plugins, filterscripts, etc.)—issue persists.

---

Potential Cause Hypothesis:
- Could this be related to desynchronization or packet loss between the client and server?
- Could an anti-cheat plugin or script be mistakenly blocking the connection?
- Could Any Issue With Cookies

---

Additional Information:
If there is a debug mode or a way to enable verbose logging, please suggest it so I can gather more information.

**Comment by najuaircrack** [comment]
Imagine you join the server, and your player ID is 0. Later, you leave the server, and another player joins, taking the same ID (0). When you try to reconnect, the server displays 'Server closed connection.

**Comment by najuaircrack** [comment]
My bad, the issue was caused by a timer. The secondsTimer was setting the player's name to another online player's name, causing OnPeerConnect to return nullptr, which led to the player being kicked.

**Comment by xdatsec** [comment]
whats the fix najuaircrack?
