### ISSUE TITLE
string params to SendDeathMessageToPlayer

### ISSUE THREAD

**Issue by hiwyn** [openmultiplayer/open.mp#1024]
How `SendDeathMessageToPlayer(playerid, killer, killee, weapon);`
recive params:
```
playerid	The ID of the player to send the death message to.
killer	The ID of the killer (can be INVALID_PLAYER_ID).
killee	The ID of the player that died.
weapon	The reason (not always a weapon) for the victim's death. Special icons can also be used (ICON_CONNECT and ICON_DISCONNECT).
```

could you guys add two more params?
killerStrName[MAX_PLAYER_NAME] and killeeStrName[MAX_PLAYER_NAME]

with this flexible way it give us more power to create stuff, i by myself got 2 ideas to stuff to do...

like
```pawn
SendDeathMessageToPlayer(playerid, killer, killee, weapon, killerStrName, killeeStrName);
```

If got the `killerStrName` param it use instead of player name and if does not have it get player name by `killer` id

**Comment by EvilShadeZ** [comment]
The RPC for death message only contains the following:
`UINT16 wKillerID, UINT16 wPlayerID, UINT8 reason`
therefore unless a client is made, this is not going to work.
