### ISSUE TITLE
https://github.com/openmultiplayer/open.mp/issues/1028#issue-2731657224

### ISSUE THREAD

**Issue by Nandi336** [openmultiplayer/open.mp#1029]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots and/or logs**
If applicable, add screenshots and/or log output to help explain your problem.

**Release version**
Put the release version of the broken build here.

**Comment by Nandi336** [comment]
Ini kota Aron asia

**Comment by Nandi336** [comment]
https://github.com/openmultiplayer/open.mp/issues/1028#issue-2731657224

**Comment by AmyrAhmady** [comment]
????????????
