### ISSUE TITLE
[BUG]:  SetVehicleParamsEx The light of the player sitting in the car is not updated.

### ISSUE THREAD

**Issue by ApostolDmitry** [openmultiplayer/open.mp#575]
# Description

If you get into the car and change light parameter, then the player will not change it only when leaving the car.

# How to re-produce this bug

*Tell us a how to re-produce this bug in steps for example:*

1. get in the car
2. change light parameter

# Relevant log output

```
None
```

# open.mp server version

5 build

# Operating system or distribution

Ubuntu 20.04

# Contact information

ApostolDMITRY#7369

# Additional information

-

**Comment by AmyrAhmady** [comment]
Is this still happening? @ApostolDmitry

**Comment by BeckzyBoi** [comment]
> Is this still happening? @ApostolDmitry

I've just tested with latest release and it's working just fine. Tested as passenger in previously unoccupied vehicle, as driver of vehicle, and then passenger again in same vehicle.

**Comment by ApostolDm** [comment]
@AmyrAhmady Hi. Fixed it ) Thanks
