### ISSUE TITLE
[BUG]: Custom Object Model fails to load in open.mp!

### ISSUE THREAD

**Issue by Highkeey** [openmultiplayer/open.mp#579]
# Custom Object Model fails to load in open.mp.

*So essentially, there is one singular custom model in my server that fails to load in open.mp, the rest of them work and the one that doesn't load in open.mp successfully loaded in SAMP.*

# How to re-produce this bug

1. *Place the files into your models folder.* [https://www.mediafire.com/file/5uedp7ejh584vak/idlewood.zip/file](url)
2. *Add this line into artconfig.txt: AddSimpleModel(-1, 19475, -1003, "idlewood.dff", "idlewood.txd");*
4. *Make sure that artwork is set to on.*
5. *Add the following text to your script:*
`CreateDynamicObject(-1003, 1927.703003, -1754.313965, 12.461000, 0.000000, 0.000000, 0.000000, -1, -1, -1, 300.0, 300.0);
SetDynamicObjectMaterial(idlewood, 3, 3653, "beachapts_lax", "sjmscorclawn");`
6. *Start the server and head over to the same location as the image attached and see if it works.*
![sa-mp-018](https://user-images.githubusercontent.com/53993440/211190109-90785845-56ed-4bb6-a8dd-b0b3159cba4d.png)

# Relevant log output

```
*N/A*
```

# open.mp server version

*RC1*

# Operating system or distribution

*Linux*

# Contact information

*Imperium#0001*

# Additional information

*This model worked on SAMP 0.3.DL but not open.mp!*

**Comment by AmyrAhmady** [comment]
Try adding it to your gamemode and report back please
See if it works that way, instead of artconfig.txt
@Highkeey

**Comment by AmyrAhmady** [comment]
It's been a very long time and there has been no reply. closing this for now, if anyone still has this issue or anything related, feel free to reply

**Comment by KirovNoName** [comment]
> It's been a very long time and there has been no reply. closing this for now, if anyone still has this issue or anything related, feel free to reply

I tried adding AddSimpleMode and AddCharModel, but the server does not seem to load them even after starting the server.

**Comment by AmyrAhmady** [comment]
Read what I suggested, do it, and report back

**Comment by sicariodll** [comment]
Given model IDs should be between 10000-20000. I faced the same issue long time ago.

**Comment by AmyrAhmady** [comment]
That's just not true at all
https://open.mp/docs/scripting/functions/AddCharModel#description
