### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: /alogin - admin panel

### ISSUE THREAD

**Issue by nikyan95** [openmultiplayer/open.mp#580]
# Description

**Hello. I ran into another problem, namely, authorization in the admin panel on the server. Everything is fine in samp. the algorithm of actions: we go to the server, write a command / login, a dialog box appears in which you need to enter a password. If everything is in order and you entered the password correctly, you should write: "You are logged in as an administrator", if you enter the command/login again, you should write "You are already logged in!" - this is the correct algorithm that works on the samp client. As for openmp, when you enter the /alogin command, a dialog box appears in which you need to enter your password, after entering the correct password, the server does not issue a text message stating that you are logged in, and the /alogin command can be used many times and it will not write "You are already logged in" - in this case, the admin commands work correctly. Sorry for my English , I'm using a translation**

# How to re-produce this behavior difference
**Please take a look at the videos I have attached to Google drive**
[https://drive.google.com/file/d/1ZNSnma8KTsFg9ClPJB-ltZuYIryXj13i/view?usp=sharing](url)
[https://drive.google.com/file/d/1rHWbCCbdlm3wgNJBlUUJs_yZrExKCW6B/view?usp=sharing](url)

# open.mp server version

*build 8?

# Operating system or distribution

Windows , localhost

# Contact information

Discord: nikyan95#6927

**Sincerely yours - the team of the Russian project Arcada Games**

**Comment by AmyrAhmady** [comment]
No reply for a long time for this unexplained issue, closing it now, please contact us on Discord or create a new issue if you got any more info to share.
