### ISSUE TITLE
[BUG]: Russian language support in the server console

### ISSUE THREAD

**Issue by MironGHW** [openmultiplayer/open.mp#583]
# Description

[
![image](https://user-images.githubusercontent.com/79435201/209658170-f24d8601-7832-4d46-aa5b-921bebd19bf1.png)
](url)

# open.mp server version

build11

# Operating system or distribution

windows10

# Contact information

M1RoN#6464

**Comment by NexiusTailer** [comment]
> Set the console text encoding to the desired encoding or just compile your script with UTF-8 encoding.

Any pawn script which contains cyrillic **must** be compiled in Windows-1251. Any other encoding including UTF-8 will produce ?????? or other artifacts in the running server. The problem is in omp server console and the way how it works with pawn script's outputs.
