### ISSUE TITLE
[BUG]: gmx / reconnect from class selection 

### ISSUE THREAD

**Issue by BeckzyBoi** [openmultiplayer/open.mp#588]
RCON gmx , or any "successful" reconnection, for players who are at class selection, causes them to to get stuck at the Verona Beach connecting screen before reaching OnPlayerRequestClass (which isn't ever called as a result). At this point the players' only option is to quit the game and rejoin.

To reproduce:

1. Enter class selection
2. Call RCON gmx , or briefly disconnect your internet until the server tries to reconnect you.
3. Wait til you're reconnected and voila!

open.mp server version:

build10 , but this has always happened at class selection since the SA-MP logo was removed and the 3 buttons (left, right, spawn) were added. Maybe even before that?

OS:

Windows 11 at present. Happens on all.

Contact:

beckzy #5936

It's an old SA-MP bug that can possibly be fixed in the omp server. My apologies if I've submitted this in the wrong place.

**Comment by AmyrAhmady** [comment]
This can not be fixed without client, because client is not signaling anything about this behavior to server and we can't possibly know it's happening

EDIT: Talked to beckzy, maybe we can add a temporary solution into Fixes component for now.

**Comment by BeckzyBoi** [comment]
SpawnPlayer inside OnPlayerDisconnect seems to resolve this without any noticable problems, although I understand that that is through the gamemode, and not the server code, and that applying the same fix through the server might not be as straight-forward?

Thanks.
