### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: IsTrailerAttachedToVehicle

### ISSUE THREAD

**Issue by gitshone** [openmultiplayer/open.mp#590]
# Description

When you attach a trailer to the truck IsTrailerAttachedToVehicle should return true (1).

# How to re-produce this behavior difference

*Tell us a how to re-produce this behavior:*

1. Slowly reverse to the trailer and attach it to the truck.
2. Check if the trailer is actually attached on the server IsTrailerAttachedToVehicle(GetPlayerVehicleID(playerid))
3. Result should be false even if it is attached.

# open.mp server version

(0.0.10.2126) build 10
28309b34dc7a8102058bccd6bc9660d7aa71a9b8

# Operating system or distribution

Tested only on windows 11.

# Contact information

CADILAB#9240

**Comment by AmyrAhmady** [comment]
Can you please confirm if this issue still exists?
