### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: SetVehicleToRespawn respawning where the last vehicle position not on created location.

### ISSUE THREAD

**Issue by eksqtr** [openmultiplayer/open.mp#591]
# Description

*Describe the behavior difference between open.mp server and SA:MP server!*
SetVehicleToRespawn is buggy sometimes where it respawn the vehicle from it's last position instead where the vehicle is being created using AddStaticVehicleEx

# How to re-produce this behavior difference
```
new TruckerVehicles;
TruckerVehicles = AddStaticVehicleEx(456,2184.2715,-2657.7344,13.7617,89.2901, Random(0, 255), Random(0, 255), 300, false);
```

Drive the vehicle around then use 

`SetVehicleToRespawn(TruckerVehicles);`

the truckervehicle should respawn at coordinate 
`2184.2715,-2657.7344,13.7617`

  where you created the vehicle using 
`AddStaticVehicleEx`

but inrandom times the truckervehicle spawn where the last vehicle positioned before you trigger the 
`SetVehicleToRespawn(TruckerVehicles);`

*Tell us a how to re-produce this behavior:*

1. Create a Server vehicle using  `AddStaticVehicleEx`
2. Drive the vehicle around the location
3. Trigger the SetVehicleToRespawn(TruckerVehicles);

# Relevant log output

https://streamable.com/rzrxaq

# open.mp server version

*What open.mp server version are you using? [Build 10
](https://github.com/openmultiplayer/server-beta/releases/tag/build10)
For a development build please specify its commit hash.*

# Operating system or distribution
Windows OS

*Tell us what operating system or distribution did you use when you did encounter this behavior difference?*

# Contact information
Oppai#6450

# Additional information

*Any additional information that could be relevant for us to know?*

**Comment by AmyrAhmady** [comment]
Fixed in next build
