### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by xunder-matth** [openmultiplayer/open.mp#592]
1. Passing custom argument for config file path (e.g. `./omp-server config.dev.json`)
2. Adding `log_file` in `config.json` so we can specify custom output file (e.g. `"log_file": "dev_logs.log"`)
3. New function - `GetVehicleOccupant(vehicleid, seat)` (pretty self-explanatory)
4. As we already have `native GetWeaponSlot(weaponid);` which provides game data maybe you can add more functions like this:
```
native GetVehicleMaxPassengers(vehicleid); // or even better "modelid"
native CountVehicleOccupants(vehicleid);
```

**Comment by AmyrAhmady** [comment]
Fixed in next build (natives are test by @NexiusTailer , the rest are done as well, if there's any issue, create a new one regarding their bugs)
