### ISSUE TITLE
Add queryflood variable from R3 server

### ISSUE THREAD

**Issue by NexiusTailer** [openmultiplayer/open.mp#599]
In LegacyConfig component (config_main.cpp), there is `Obsolete` variable type which declares some of them. Such variables as `conncookies`, `worldtime` and others is under this type. Would be good to add missed `queryflood` which probably also should be in this section if it's not used here but still exist in SA-MP as int variable.

UPD: On the other hand, I also found [game.use_instagib](https://github.com/openmultiplayer/open.mp/blob/master/Server/Source/core_impl.hpp#L75), [game.use_zone_names](https://github.com/openmultiplayer/open.mp/blob/master/Server/Source/core_impl.hpp#L83) and [game.death_drop_amount](https://github.com/openmultiplayer/open.mp/blob/master/Server/Source/core_impl.hpp#L65). Looks like it's also obsolete and has no effect, but there were no such variables in SA-MP server at all. Is it done just to reserve the names or there are plans to add any effect to them in the future?

**Comment by Hual** [comment]
This should be fixed by #683
