### ISSUE TITLE
GetVehicleParamsEx all true by default

### ISSUE THREAD

**Issue by BeckzyBoi** [openmultiplayer/open.mp#602]
At default in SA-MP GetVehicleParamsEx parameters are all -1 until they are set. Is this causing vehicle params in omp to be true by default? Now that they're boolean they should probably be false when unset (-1) ?

**Comment by Y-Less** [comment]
https://github.com/openmultiplayer/omp-stdlib/blob/910d2c530ab6abb81d0c1cb72e6f71be2a94d33a/open.mp.inc#L259-L265

**Comment by Hual** [comment]
Is this an actual issue or can it be closed?
