### ISSUE TITLE
public OnPlayerClickTextDraw(playerid, Text:clickedid)

### ISSUE THREAD

**Issue by Victe221** [openmultiplayer/open.mp#607]
Can you check in any way callback OnPlayerClickTextDraw(playerid, Text:clickedid) ?
I think there's some problem, because when I run open.mp server then server calling over and over callback OnPlayerClickTextDraw and spam in log:  [Warning] client exceeded 'messageslimit' 127.0.0.1:60003 (675) Limit: 500/sec

When I commented this callback then everything's okay...

My code:

new Text:playerTD[MAX_PLAYERS];

public OnPlayerClickTextDraw(playerid, Text:clickedid)
{
	if(clickedid == playerTD[playerid])
 	{
            //here is SendClientMessage, some variable etc..
        }
        return 1;
}

**Comment by NexiusTailer** [comment]
Did you test this code on samp server to compare the behaviour?

**Comment by Victe221** [comment]
Yup. And on samp server everything is working. I've updated my gamemode and includes with upgrade/qawno and all code is okay, except OnPlayerClickTextDraw xD

**Comment by AmyrAhmady** [comment]
when your server is calling OnPlayerClickTextDraw over and over, print textdraw ID, and see what it is
