### ISSUE TITLE
Qawno compiler automaticaly changes special characters

### ISSUE THREAD

**Issue by Victe221** [openmultiplayer/open.mp#612]
Qawno still changes special characters and polish chars "ą ę ó ł ż ź ś ć" to "?" and font change didn't help with it, because open.mp server still changes chars to "?"

**Comment by Southclaws** [comment]
The editor, compiler and server can all solve this problem quite easily but the main issue is that the sa-mp client cannot render anything other than ANSI codepage-encoded sequences. Not Unicode. So Qawno, Pawno, Sublime Text, VS Code, The Pawn compiler, the sa-mp server and the open.mp server cannot really do anything to solve this.

**Comment by Victe221** [comment]
Hmm. I compiled map with pawno.exe(with open.mp includes) not qawno.exe and now every chars work perfectly. So I think it's a qawno.exe bug

**Comment by Southclaws** [comment]
This is likely a codepage configuration issue then, I'm not sure how Qawno handles this.

**Comment by AmyrAhmady** [comment]
Open an issue on Qawno repository, closing this in here.
