### ISSUE TITLE
Toolchain for armv7 is broken

### ISSUE THREAD

**Issue by jeanluc162** [openmultiplayer/open.mp#613]
When using the included build.sh script to build for armv7 it fails with the following output:
```
/usr/bin/clang-10  -I. -Iinclude -fPIC -pthread -O3 -Wa,--noexecstack -Qunused-arguments -O3 -fPIC -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/etc/ssl\"" -DENGINESDIR="\"//lib/engines-1.1\"" -DNDEBUG -DNDEBUG -DNDEBUG -MMD -MF crypto/armcap.d.tmp -MT crypto/armcap.o -c -o crypto/armcap.o crypto/armcap.c
In file included from crypto/armcap.c:18:
crypto/arm_arch.h:55:6: error: "unsupported ARM architecture"
#    error "unsupported ARM architecture"
     ^
1 error generated.
make[1]: *** [Makefile:831: crypto/armcap.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/user/.conan/data/openssl/1.1.1q/_/_/build/17df300ceabea4231cc147d126ace6e7977e852f/src'
make: *** [Makefile:174: all] Error 2
openssl/1.1.1q: 
openssl/1.1.1q: ERROR: Package '17df300ceabea4231cc147d126ace6e7977e852f' build failed
openssl/1.1.1q: WARN: Build folder /home/user/.conan/data/openssl/1.1.1q/_/_/build/17df300ceabea4231cc147d126ace6e7977e852f/build-release
ERROR: openssl/1.1.1q: Error in build() method, line 729
	autotools.make()
	ConanException: Error 2 while executing make -j2
CMake Error at SDK/lib/cmake-conan/conan.cmake:529 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  SDK/lib/cmake-conan/conan.cmake:766 (old_conan_cmake_install)
  SDK/lib/cmake-conan/conan-omp.cmake:70 (conan_cmake_run)
  lib/CMakeLists.txt:120 (conan_omp_add_lib_opt)
```

**Comment by Hual** [comment]
What cmake options are you using?

**Comment by jeanluc162** [comment]
I did not specify any, I just executed the `build.sh`-script in the `docker`-folder with armv7 as target arch. It works this way for the default arch (x86)

**Comment by AmyrAhmady** [comment]
try using `armv7hf` instead

**Comment by jeanluc162** [comment]
> try using `armv7hf` instead

This leads to the same result. I've also already tried armv6 and armv8.

**Comment by jeanluc162** [comment]
Could this maybe be related to [this Issue from the conan repo](https://github.com/conan-io/conan-center-index/issues/99)?

**Comment by AmyrAhmady** [comment]
Depends, as I've told @Disinterpreter it seems like a conan issue when you try to cross build, but on bare metal machine (I don't know if you are using an ARM machine or not) it works, without using docker of course

basically steps do to on an ARM machine:
```
      - name: Generate build files
        run: |
          export CC=clang
          export CXX=clang++
          export OMP_BUILD_VERSION=$(git rev-list $(git rev-list --max-parents=0 HEAD) HEAD | wc -l)
          export OMP_BUILD_COMMIT=$(git rev-parse HEAD)
          mkdir build && cd build && cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DTARGET_BUILD_ARCH=armv7 ..
      - name: Build
        run: |
          export CC=clang
          export CXX=clang++
          cd build
          ninja
```
obviously you need the right packages too, 32bit libraries, cmake, ninja, clang, python and conan

**Comment by AmyrAhmady** [comment]
As it turns out it's not really related to conan (hopefully)
We are having progress regarding this and cross compiling

**Comment by jeanluc162** [comment]
If I'm understanding this correctly this means there is no way atm to add a build action for ARM as Actions can only run on x86_64? I was planning in creating a PR for this...

**Comment by Disinterpreter** [comment]
> If I'm understanding this correctly this means there is no way atm to add a build action for ARM as Actions can only run on x86_64? I was planning in creating a PR for this...

Did you try to build on debian armel natively?

**Comment by jeanluc162** [comment]
> Did you try to build on debian armel natively?

No I have not, as that is not my goal - expanding the GitHub-Actions so ARM-Builds are generated automatically

**Comment by Disinterpreter** [comment]
> > Did you try to build on debian armel natively?
> 
> No I have not, as that is not my goal - expanding the GitHub-Actions so ARM-Builds are generated automatically

oh, ok. No way at the moment.

**Comment by AmyrAhmady** [comment]
We now have arm CI builds, please take a look at archives here: https://github.com/openmultiplayer/open.mp/actions/runs/5232220321

and let me know if they run fine @Disinterpreter @jeanluc162
