### ISSUE TITLE
GetVehicleLastDriver should return INVALID_PLAYER_ID if invalid vehicle id is passed as argument

### ISSUE THREAD

**Issue by xunder-matth** [openmultiplayer/open.mp#614]
If we pass invalid `vehicleid` as an argument to `GetVehicleLastDriver` (and probably more) function we get `0` as returned value.

```pawn
main() {
 CreateVehicle(400, 0.0, 0.0, 0.0, 0.0, -1, -1, -1); // creating vehicle id 1
 printf("%d", GetVehicleLastDriver(1)); // INVALID_PLAYER_ID
 printf("%d", GetVehicleLastDriver(2 /*Not created veh*/)); // 0
}
```

Currently every failed validation will return `0`. Since `0` is valid player id it can be confusing if scripters doesn't validate it using `IsValidVehicle`.

**Comment by AmyrAhmady** [comment]
Fixed
