### ISSUE TITLE
While using Windows 1250 or 1252 encoding a bug occurs with texts that contains unicode characters

### ISSUE THREAD

**Issue by Mortyyka** [openmultiplayer/open.mp#617]
# Description

While using encoding **Windows 1250 or Windows 1252** this bug occours.

# How to re-produce this bug

Compile your script using **Windows 1250 or Windows 1252**, print out a text that contains unicode charaters in this example it was: **árvíztűrő tükörfúrógép**.

# Relevant log output

Console Output (Using Windows 1250 or Windows 1252)
[Image #1](https://asked.hu/XzkovGSD)

The same thing but in a text:

```
[Info] [OMP - Test]: Testing unicode characters:
[Info] [OMP - Test]: Testing unicode characters:
[Info] [OMP - Test]: Testing unicode characters:
[Info] [OMP - Test]: Testing unicode characters:
[Info] [OMP - Test]: Testing unicode characters:
[Info] [OMP - Test]: Testing unicode characters:
[Info] [OMP - Test]: Testing unicode characters:
[Info] [OMP - Test]: Testing unicode characters:
[Info] [OMP - Test]: Testing unicode characters:
[Info] [OMP - Test]: Testing unicode characters:
[Info] [OMP - Test]: Testing unicode characters:
[Info] [OMP - Test]: Testing unicode characters:
[Info] [OMP - Test]: Testing unicode characters:
[Info] [OMP - Test]: Testing unicode characters:
[Info] [OMP - Test]: Testing unicode characters:
[Info] [OMP - Test]: Testing unicode characters:
[Info] [OMP - Test]: Testing unicode characters:
[Info] [OMP - Test]: Testing unicode characters:
[Info] [OMP - Test]: Testing unicode characters:
[Info] [OMP - Test]: Testing unicode characters:
```

Note that in the server log it shows the whole text, including the unicode characters.

This is how the original message should look like:

```
[Info] [OMP - Test]: Testing unicode characters: árvíztűrő tükörfúrógép on OMP - RC2, text without unicode: arvizturo tukorfurogep
```

# open.mp server version

OMP RC2 - Latest Release

# Operating system or distribution

Windows 10

# Contact information

Mortyyka キング#1972

# Additional information

While using UTF-8 it works however, ingame the text becomes scuffed, example below.

```
[23:15:51] Testing unicode characters: ĂˇrvĂ­ztĹ±rĹ‘ tĂĽkĂ¶rfĂşrĂłgĂ©p on OMP - RC2, text without unicode: arvizturo tukorfurogep
```

**Comment by Mortyyka** [comment]
I would also like to add this, this is the difference between b10 and RC2.
https://boobies.icu/vajxC4B7

**Comment by AmyrAhmady** [comment]
Fixed in next build.
