### ISSUE TITLE
IsPlayerUsingGamepad as built-in native

### ISSUE THREAD

**Issue by NexiusTailer** [openmultiplayer/open.mp#618]
Would be great to add a native like `IsPlayerUsingGamepad` or `IsPlayerUsingJoypad` as built-in native to detect if player keys have anything than 0 or |128| in up/down and left/right states ([example of implementation](https://github.com/udan11/samp-anticheat/blob/master/src/watchguard/impl/Watchguard_Joypad.pwn)). This will help adapting in-game control tips for players from android or real gamepads and make other gameplay improvements for mobile-only servers.

The propose was considered relevant since another native `IsPlayerUsingOfficialClient` was added recently.

**Comment by Disinterpreter** [comment]
If we talk about gamepads, it's better to add more natives. Like for getting info about device: xinput or sony and etc...

**Comment by NexiusTailer** [comment]
> Like for getting info about device: xinput or sony and etc...

Well I doubt it's possible without client changes in near future. Checking keys sync parameter for intermediate values (which is a thing for gamepad sticks but not for keyboard keys) can be done even now as the key values (up/down/left/right) are already passed in every main synchronization.
