### ISSUE TITLE
GetDetailedPlayers from SAMP QUERY API doesn't WORK on OPENMP!

### ISSUE THREAD

**Issue by mixedthoughts** [openmultiplayer/open.mp#619]
Hi.

GetDetailedPlayers, via php or websites, DOES NOT WORK ON open-mp.

The query is not added to open-mp.

Please add it.

We can't track players who are playing ingame, can't track THEIR SCORE AND PING and that's very bad.

It always returns ZERO. no one is ingame, even if they are. Works completely fine on samp.

Check this: https://www.game-state.com/141.95.3.158:7777/

**Comment by AmyrAhmady** [comment]
You can use query type `c` and you will get your list of players, which is exactly the data game-state.com is trying to show
![image](https://user-images.githubusercontent.com/34688664/213361725-3746e184-fd29-4861-b7ee-32b53dfd4065.png)

This is not something for us to fix, I'll see if I can contact them

**Comment by realStandal** [comment]
Ik this is old, but I came across some trouble running into wanting a list of players and their ID. It _is_ something for "y'all" (Open.MP) to fix. Y'all don't mimic [SA:MP's query mechanism](https://open.mp/docs/tutorials/QueryMechanism?utm_source=chatgpt.com) exactly, namely the `d` opcode. https://github.com/openmultiplayer/open.mp/blob/faf5db10ab0f511b0194470050bf6465b0e9d7a6/Server/Components/LegacyNetwork/Query/query.cpp#L287

I'll open a PR, but it's not high on my priorities so I'm more just noting the issue for others right now.
