### ISSUE TITLE
GametextForPlayer not work

### ISSUE THREAD

**Issue by plakapenka** [openmultiplayer/open.mp#621]
GametextForPlayer not work
`GameTextForPlayer(playerid, "~W~Siren ~G~on", 1000, 3);`

in samp - work

**Comment by AmyrAhmady** [comment]
Please try it on a clean script first
```cpp
#include <a_samp>

main()
{
}

public OnPlayerSpawn()
{
    GameTextForPlayer(playerid, "~W~Siren ~G~on", 1000, 3);
}
```
if it doesn't show, please report back

**Comment by plakapenka** [comment]
The fact is that Fixes makes an imitation of GameText using textdraws, but I don’t have them.
Removing Fixes solves the problem in my case. Thanks Amyr Ahmady.
Sorry that I decided to supplement the answer after such a long time)) Suddenly it will be useful to someone
