### ISSUE TITLE
[BUG] Player die in invehicle by vehicle explosion

### ISSUE THREAD

**Issue by enterprice2** [openmultiplayer/open.mp#622]
HI, i have a bug on my server
OMP RC2

When you die inside vehicle by explosion and you got spawn inside an interior on your screen apper a visual bug, if i spawn again the visual bug dissaper

[[/url]](https://imgur.com/a/8bbCIiM)[Imgur: The magic of the Internet](https://imgur.com/a/8bbCIiM)[url=https://imgur.com/a/8bbCIiM]

**Comment by AmyrAhmady** [comment]
Closing this for now, if anyone still has this issue or anything related, feel free to reply
