### ISSUE TITLE
Using SetPlayerName in OnPlayerDisconnect callback

### ISSUE THREAD

**Issue by neverm1ndo** [openmultiplayer/open.mp#625]
If you'll try to use ``SetPlayerName`` in ``OnPlayerDisconnect`` callback, in the SAMP client, disconnected player will be shown in the list of players, and the number of players on the server will be displayed as 1/32 for example, although there are actually no players on the server. It's kind of "phantom", or something like that.

**Comment by AmyrAhmady** [comment]
Fixed in next build
