### ISSUE TITLE
GetVehicleRotationQuat doesn't store data for unoccupied/trailer vehicle

### ISSUE THREAD

**Issue by NexiusTailer** [openmultiplayer/open.mp#626]
OMP server doesn't store quaternion data at all from any sync but only driver (incar), while SA-MP server does.

SA-MP server, in turn, has bugs with corrupted 3rd field in GetVehicleRotationQuat in unoccupied sync and the fact that it gets quaternions of the truck instead of a trailer for GetVehicleRotationQuat, but still. These all can be fixed, and the omp server can start passing relevant quats from the current sync vehicle is updating by.

**Comment by AmyrAhmady** [comment]
Fixed in next build.
