### ISSUE TITLE
Static analysis of the project code

### ISSUE THREAD

**Issue by NexiusTailer** [openmultiplayer/open.mp#627]
I'm remember that during the development process you were find errors at least a couple of times with dynamic code analyzers like Valgrind. However, I suppose a lot of other bugs could also be found with the help of a static analyzer, which could point to those places that are inaccessible to proper detection by dynamic analysis. PVS-Studio will be probably the choice.

**Comment by AGraber** [comment]
I don't have a PVS-Studio license, and I think the rest of the team doesn't. 

Personally I've seen a lot of spam around GitHub from commit farmers introducing illogical changes suggested by static analyzers ([example](https://github.com/skyline-emu/skyline/pull/1491)) but I think we're open to any changes that make sense.

**Comment by NexiusTailer** [comment]
> I don't have a PVS-Studio license, and I think the rest of the team doesn't.
> 
> Personally I've seen a lot of spam around GitHub from commit farmers introducing illogical changes suggested by static analyzers ([example](https://github.com/skyline-emu/skyline/pull/1491)) but I think we're open to any changes that make sense.

Well, this is pretty funny indeed. However it is known that static analyzers should be pretty much configured (for the project personally to omit most of the false positives) before it can become a really effective bugfinding tool for a project. Anyway, PVS-Studio has some trial mode or something like this (program key is requested from the developers and seems like it's not difficult to get it for an open source project as they're interested in such cases, especially if this is kinda popular case they can help with and promote yourself this way too).
