### ISSUE TITLE
Unused `LogLevel::Debug` and a place where it can be used

### ISSUE THREAD

**Issue by NexiusTailer** [openmultiplayer/open.mp#634]
`LogLevel::Debug` in `vlogLnInternal` ([here](https://github.com/openmultiplayer/open.mp/blob/426bb8e9c3180b781c9cdd40ba9bf5d5a6af0e32/Server/Source/core_impl.hpp#L1692-L1695)) doesn't have even a single place where it's actually used. However, at least one place where it can be used is the following code:

https://github.com/openmultiplayer/open.mp/blob/e6c5de0962413489c0035482babe98ca367102cb/Server/Components/LegacyNetwork/legacy_network_impl.cpp#L579-L584

So it should probably omit `#ifdef _DEBUG` check and use `network->core->logLn(LogLevel::Debug, ` instead.

**Comment by AmyrAhmady** [comment]
Done.
