### ISSUE TITLE
Give access to some extra sync data in new built-in natives

### ISSUE THREAD

**Issue by NexiusTailer** [openmultiplayer/open.mp#635]
Would be great to add a native like:
* GetVehicleParamsForPlayer. Just the getter for already existed SetVehicleParamsForPlayer
* GetPlayerAnimationFlags or GetPlayerAnimFlags. The information about anim flags is stored in [onfoot synchronization](https://github.com/katursis/Pawn.RakNet/wiki/OnFootSync)
* IsPlayerInDriveByMode. The drive-by flag is stored in [passenger synchronization](https://github.com/katursis/Pawn.RakNet/wiki/PassengerSync)

Others seems to be implemented when porting YSF stuff, but these two were mentioned by me on CBT in [this issue](https://github.com/openmultiplayer/server-beta-test/issues/20) among other functions from YSF (and probably were missed just because I didn't notice it's not from a plugin itself, but still useful to be added by default).

**Comment by AmyrAhmady** [comment]
Except `GetVehicleParamsForPlayer`, the rest are done, and tested by Nexius himself
the remaining native will be added alongside other YSF native additions, closing this issue in favor of YSF todo list one
