### ISSUE TITLE
[BUG]printf and print

### ISSUE THREAD

**Issue by ghost** [openmultiplayer/open.mp#643]
"printf" and "print" functions cannot print Chinese characters, but it is possible to print Chinese characters in SA-MP (San Andreas Multiplayer).  Perhaps characters from other countries cannot be printed as well.

**Comment by NexiusTailer** [comment]
Related to #637 #617 and #583

**Comment by ghost** [comment]
Visual Studio Code
Files: Encoding: Simplified Chinese (GB2312)

**open.mp server version**: R2

**code:**
`main() {
	print("print中文测试!");
	printf("printf中文测试 %d", 1);
}`

**output:**
[2023-03-12T21:22:43+0800] [Info] print
[2023-03-12T21:22:43+0800] [Info] printf
[2023-03-12T21:22:43+0800] [Info] Legacy Network started on port 7777

**Comment by AmyrAhmady** [comment]
Fixed in next build.
