### ISSUE TITLE
A couple of questions about RPCs

### ISSUE THREAD

**Issue by NexiusTailer** [openmultiplayer/open.mp#646]
I checked RPC structures and have a couple of questions about them:
1. Doesn't this seem weird that "allow" parameter here ([click](https://github.com/openmultiplayer/open.mp/blob/e6c5de0962413489c0035482babe98ca367102cb/Shared/NetCode/class.hpp#L147)) is a bit redundant in its variable size? Mostly such variables are uint8, just like above with Selectable parameter in RPC PlayerRequestClassResponse. I suppose it was a mistake or there is (an)other parameter(s) after the first found.
2. Custom models from 0.3.DL are always use redirecting way of downloading content ([click](https://github.com/openmultiplayer/open.mp/blob/e6c5de0962413489c0035482babe98ca367102cb/Shared/NetCode/custommodels.hpp#L74)) as it's constantly set to 6 while there is also type 1 for this parameter and seems it's used in samp server to download models directly.
3. RPC SetPlayerAttachedObject ([click](https://github.com/openmultiplayer/open.mp/blob/e6c5de0962413489c0035482babe98ca367102cb/Shared/NetCode/object.hpp#L277)) has AttachmentData.model parameter as UINT32 even if it is 0.3.DL version. It should probably be INT32 to be able attaching custom objects.

**Comment by ksenonadv** [comment]
1. No.
2. Direct downloads are slow and CPU intensive. We choose to not implement them.
3. Doesn't really matter since it's stored as an int (signed) and of same size, but yeah it can be updated for sake of correctness.

**Comment by NexiusTailer** [comment]
As for the third, 0.3.DL object models have negative IDs so I noticed it only because of this reason. I didn't really test it in-game if samp server can attach custom objects via SetPlayerAttachedObject correctly, but probably should.
