### ISSUE TITLE
[BUG] sqlite characters save problem

### ISSUE THREAD

**Issue by ghost** [openmultiplayer/open.mp#650]
```c++
new DB:testdb;
public OnGameModeInit()
{
    testdb = DB_Open("test.db");
    if(testdb) 
    {
        DB_ExecuteQuery(testdb, "CREATE TABLE IF NOT EXISTS \"test\" (\"name\" TEXT DEFAULT NULL)");
        DB_ExecuteQuery(testdb, "INSERT INTO `test` (`name`) VALUES ('中文')");
        DB_ExecuteQuery(testdb, "INSERT INTO `test` (`name`) VALUES ('chinese character')");
    }
    return 1;
}
``` 
[![8-R0-D6-KM3-EIR-RNBIC-I-IW.png](https://i.postimg.cc/Rh167cbg/8-R0-D6-KM3-EIR-RNBIC-I-IW.png)](https://postimg.cc/2L6SmBYW)

**open.mp server version**
RC2

**Operating system or distribution**
win11

**Comment by AmyrAhmady** [comment]
I saw you fixed it on Discord after finding the solution, if possible please repost it here. I'm closing this
