### ISSUE TITLE
CreateVehicle still doesn't create trains.

### ISSUE THREAD

**Issue by Mergevos** [openmultiplayer/open.mp#651]
As the title says. Try it yourself with CreateVehicle somewhere.

**Comment by ghost** [comment]
Trains can only be added with [AddStaticVehicle] and [AddStaticVehicleEx]

**Comment by Mergevos** [comment]
> Trains can only be added with [AddStaticVehicle] and [AddStaticVehicleEx]

https://discord.com/channels/231799104731217931/231799180127895553/1087770620139417610

**Comment by Alasnkz** [comment]
https://github.com/openmultiplayer/open.mp/blob/master/Server/Components/Vehicles/vehicles_impl.hpp#L384-L387

By design, though it doesn't change anything if this check is removed.

**Comment by Hual** [comment]
This should be closed with wontfix
