### ISSUE TITLE
Client keeps receiving GiveMoney and ResetMoney RPCs

### ISSUE THREAD

**Issue by plakapenka** [openmultiplayer/open.mp#653]
I'm logging RPC GiveMoney and ResetMoney (on the client side). It floods like crazy, despite the fact that I don't have a single call to these functions in my mod.
This happens after death.
It doesn't happen with removing Fixes component

**Comment by Y-Less** [comment]
What's the bug?

**Comment by Hual** [comment]
If you don't want this behaviour just don't use the Fixes component

**Comment by Hual** [comment]
This should be closed with wontfix
