### ISSUE TITLE
Server crash when CrashDetect is versions: 4.21, 4.22(Y_Less fork)

### ISSUE THREAD

**Issue by shierru** [openmultiplayer/open.mp#664]
### Issue description:
For some unknown reason the server crashes when connecting crashdetect:
`[Info] Loading plugin: crashdetect`
 `[Info]   CrashDetect plugin 4.21`
 `[Info] [debug] Server crashed while executing <unknown>`
 `[Info] [debug] AMX backtrace:`
 `[Info] [debug] #0 000000a0 in public OnGameModeInit () in <unknown>`
 `[Info] [debug] Registers:`
 `[Info] [debug] EAX: 0387e404 EBX: 00000010 ECX: 00000000 EDX: 00020ed8`
 `[Info] [debug] ESI: 00d2e090 EDI: 03858e60 EBP: 001ff614 ESP: 001ff5b0`
 `[Info] [debug] EIP: 00000000 EFLAGS: 00210212`
 `[Info] [debug] Stack:`
 `[Info] [debug] ESP+00000000: 64177d55 00d2e090 0387e404 038258a8`
 `[Info] [debug] ESP+00000020: 00000788 641d1028 03858c50 641532d8`
 `[Info] [debug] ESP+00000040: 00020ed8 00024ed4 03859548 00024ec8`
 `[Info] [debug] ESP+00000060: 00024ebc 001ff678 641689f5 00d2e090`
 `[Info] [debug] ESP+00000080: 007f0d08 03858c8c 03858c50 00000006`
 `[Info] [debug] ESP+000000a0: 00d2e090 00000001 00000000 00000000`
 `[Info] [debug] ESP+000000c0: 007f0c48 00d2e090 001ff68c 64170f0c`
 `[Info] [debug] ESP+000000e0: 65eaaaf1 00d2e090 001ff6d4 00000002`
 `[Info] [debug] ESP+00000100: 007f0cc8 007f0ce4 65ea2813 007f2368`
 `[Info] [debug] ESP+00000120: 65e90969 00000000 f9fd11df 007f0c48`
 `[Info] [debug] ESP+00000140: 00d2e088 00000001 001ff6f8 001ff6dc`
 `[Info] [debug] ESP+00000160: 00000012 0000010f 786d612e 006d0000`
 `[Info] [debug] ESP+00000180: 007f0ca8 00750000 0000000f 0000000f`
 `[Info] [debug] ESP+000001a0: 00000014 0000001f 00000006 00000002`
 `[Info] [debug] ESP+000001c0: 001ff758 0000000f 00000002 0000000f`
 `[Info] [debug] ESP+000001e0: 00d2e088 001ff6f8 001ff7f8 65ea3510`
 `[Info] [debug] ESP+00000200: 001ff810 65e99b7f 001ff7d8 00000001`
 `[Info] [debug] ESP+00000220: 007f0c48 007f0d78 656d6167 65646f6d`
 `[Info] [debug] ESP+00000240: 0000000f 001ff7c0 001ff864 65ea3560`
 `[Info] [debug] ESP+00000260: 001ff87c 65ebf5f3 001ff838 007f0d08`
 `[Info] [debug] ESP+00000280: 0000000d 03825c08 03825b38 03825b40`
 `[Info] [debug] ESP+000002a0: 00000008 007f0c48 00000001 00000000`
 `[Info] [debug] ESP+000002c0: 0305e074 0305de10 3034322e 001ff9b4`
 `[Info] [debug] ESP+000002e0: 006d09d0 00000001 0000000f 0272ee00`
 `[Info] [debug] ESP+00000300: 00000000 0000000f 025f6078 0272ecd4`
 `[Info] [debug] ESP+00000320: 00002e31 001ff9c0 00000000 0000000f`
 `[Info] [debug] ESP+00000340: 00000000 0000000f 0272ee84 0272ee64`
 `[Info] [debug] ESP+00000360: 6e657000 20706d2e 2e302e31 001ff900`
 `[Info] [debug] ESP+00000380: 007edfd8 20700039 2e302e31 001ff900`
 `[Info] [debug] ESP+000003a0: 20706d2e 2e302e31 001f0031 00000012`
 `[Info] [debug] ESP+000003c0: 76726573 00007265 00000015 0000001f`
 `[Info] [debug] ESP+000003e0: 0305e074 025f6020 001ff884 001ffc34`

I tried CrashDetect 4.22 from the repository [click](https://github.com/Y-Less/samp-plugin-crashdetect), but the result is exactly the same.

### Workspace Information:

* Server version: RC2
* Compiler version: 3.10.11
* Crashdetect version: 4.21, 4.22(Y_Less fork)
* Operating System: Windows 10

**Comment by AmyrAhmady** [comment]
1. What about older versions of crashdetect?
2. What are you compiling your script with? Are you using qawno shipped with windows package?
3. Are you using JIT plugin?

**Comment by shierru** [comment]
1. Tried version 4.19.3, lower not tried
2. I compile my script with a modified compiler [click](https://github.com/openmultiplayer/compiler) 
And so I work in Visual Studio Code, arguments task build: `"'-;+'", "'-(+'", "'-\\'", "'-Z-'",
"'-i${workspaceRoot}/include/omp-stdlib'",
"'-i${workspaceRoot}/include/stdlib'",
"'-i${workspaceRoot}/include/YSI-Includes'",
"'-i${workspaceRoot}/include/mdialog'",
"'-i${workspaceRoot}/include'",
"'-d2'", "'-O2'", "'-t4'", 
"'-o${workspaceRoot}/server/gamemodes/main'",
"'${workspaceRoot}/source/main.pwn'"`
3. No

**Comment by AmyrAhmady** [comment]
@shierru please remove -O2 and report it back
IIRC new optimization level can break crashdetect (plugin does not support it)

**Comment by shierru** [comment]
Thank you, you should have dropped the task build :)
