### ISSUE TITLE
Kick doesn't properly disconnect a player under x64 build

### ISSUE THREAD

**Issue by NexiusTailer** [openmultiplayer/open.mp#665]
Just kick an existing player with any method (would it be Kick function from your pawn script or the rcon command), the player will see "Server closed the connection" message in his game but there will be no any disconnect message in the server console about it, as well as this player won't be able to reconnect to the server. Seems like his connection somehow keeps alive or something is hanging there after kicking a player.

Tested on:
- The latest artifact from actions, but it's reproducible on any recent ones.

- Windows 64-bit server build (my machine is Windows 10 Pro 22H2).
  - Linux x64 build wasn't tested at this moment.

**Comment by AmyrAhmady** [comment]
TEsted by @NexiusTailer himself, seems to be okay now in PR #671 , so it is fixed in next build.
