### ISSUE TITLE
GetVehicleZAngle returns the train's static turn into a variable

### ISSUE THREAD

**Issue by NoPressF** [openmultiplayer/open.mp#678]
Hi, the GetVehicleZAngle function does not work correctly with trains.

For example:
I spawned the train using AddStaticVehicle and after getting the angle of rotation, it displays the angle that was set at spawn, but GTA itself turns it in the other direction. If I sit in it, the train's turning angle will be updated.

I think you will need the coordinates where I tested it all.

- `Model 537`
- `Coords: 2769.25, 466.99, 8.28`
- `Angle: 0.0`

**Comment by Y-Less** [comment]
Do you mean the game's auto-alignment of trains to the tracks?  If so, it can be solved, but is a fairly big job.

**Comment by Y-Less** [comment]
Will basically involve parsing the track definition files and using the same alignment algorithm as the game itself.

**Comment by NoPressF** [comment]
Well, for example, the GetVehicleZAngle function gets the angle of rotation of the vehicle along the z axis.  And the train can't get what it actually is.

**Comment by NoPressF** [comment]
I wrote an algorithm that roughly gets the degree of a train using the given track coordinates, but the algorithm doesn't accurately calculate the angle as it should.  It happens that it is wrong by 5 degrees, sometimes by 1 degree.

**Comment by Hual** [comment]
Is this an omp issue or a sa-mp issue? Please attach the correct label

**Comment by NoPressF** [comment]
This is issue from sa-mp, but I think it can be fixed in open-mp.

**Comment by NexiusTailer** [comment]
> This is issue from sa-mp, but I think it can be fixed in open-mp.

As we talked before, I thought it made sense to report any similar issues (even if they affected samp server as well), but seems like this case is about what the **client** sends to the server and what not. If the angle of the train is not passed in driver sync (not speaking about unoccupied or trailer sync types, they are not callable for trains at all), so if it's not passed anywhere by the client, a really working and proper fix is only available on the client side.

**Comment by Hual** [comment]
Should be marked as samp bug
