### ISSUE TITLE
Latest build from actions gives a couple of errors in log

### ISSUE THREAD

**Issue by NexiusTailer** [openmultiplayer/open.mp#679]
**Describe the bug**
Starting from [this build](https://github.com/openmultiplayer/open.mp/actions/runs/5298835448) there appear new errors in the server console after it's started:

![image](https://github.com/openmultiplayer/open.mp/assets/13169094/a2bbf898-7080-4df0-a868-ebe21d6de6dc)

**To Reproduce**
Nothing special, just start the server.

**Screenshots and/or logs**
```
[16:15:16] [Info] Failed to announce legacy network to open.mp list.
	[Server Error] Status: 406
	[Server Error] Message: {"error":"failed to query server: socket read timed out"}
```

**Commit hash in master**
[62fc8bf](https://github.com/openmultiplayer/open.mp/commit/62fc8bfa732094ad9b8f01d6c7bdd701d75bef91)

**Additional information**
Reproduces on: win32 omp server under Windows 10 22H2
Used compiler flags: `-d2 -O2`

**Comment by AmyrAhmady** [comment]
Latest build has **announce** mechanism fixed so when HTTP request call is failed, it shows the error code and message in console, they are HTTP response from open.mp server list api

**Comment by NexiusTailer** [comment]
So this behaviour is ok now and I can close the issue?

**Comment by AmyrAhmady** [comment]
Don't close it yet, so I keep this as a reminder to change those texts. Reading them again now makes me feel a lot of people are going to complain/ask why their servers are not working and blaming it on announce's HTTP call

**Comment by NexiusTailer** [comment]
@AmyrAhmady I also found that the latest fixes bring two warnings on a single used legacy config option instead of one warning as it was before:

![image](https://github.com/openmultiplayer/open.mp/assets/13169094/97bbc45c-86dd-489b-bc8f-02d84be7f5d4)

Not sure if I should open the whole issue for this, but still it worth noticing that there were only one warning (like for the other variables below) before the recent changes. The server was started without any CLI arguments, just with legacy server.cfg and obtaining some legacy options (GetConsoleVarAs*) from a samp script.

**Comment by AmyrAhmady** [comment]
Do you have any SendRconCommand native call there using "rcon" command? to enable/disable it? @NexiusTailer

**Comment by NexiusTailer** [comment]
Yes, but do they have different "flags" about deprecation now? I thought it's not.

**Comment by Hual** [comment]
This is intended, one warning is for using GetConsoleVarAs* with a deprecated name and the other is for using a console command to set a var with a deprecated name

**Comment by Hual** [comment]
Can this issue be closed? I've opened a PR with a better message
