### ISSUE TITLE
user remains in the list of players

### ISSUE THREAD

**Issue by nazpol9** [openmultiplayer/open.mp#688]
After a player leaves the server, he can still see himself in the list of players in the SAMP client.
![image](https://github.com/openmultiplayer/open.mp/assets/61046385/60d6605c-f46a-44f0-b80f-f0620fd17d6f)
This is not a temporary phenomenon. It remains until the server restarts.

open.mp build [v1-RC2](https://github.com/openmultiplayer/open.mp/tree/v1-RC2)
samp03svr 0.3dl
hosted on linux (ubuntu 22.04)

**Comment by AmyrAhmady** [comment]
Please use this version of nightly builds and report back
https://github.com/openmultiplayer/open.mp/actions/runs/5369293925#artifacts

**Comment by RiccardoMorreti** [comment]
I installed the last night build, the bug is relevant

**Comment by AmyrAhmady** [comment]
We'll continue in #754
