### ISSUE TITLE
vehicle alarm bug

### ISSUE THREAD

**Issue by iamjexcdevvv** [openmultiplayer/open.mp#689]
Hi I want to get a following updates about this bug if this has a fix but IG it has of course so basically this is what happens:

I have a system that the vehicle will alarm if they trying to turns the engine on that its not belong to them, Ex. Player A (not owner) turns the engine on of the vehicle then the alarm sound starts to play and lets say there are 2 players (Player A and B) in the scenario so player B can hear the alarm sound aswell but the problem is when the player B as not the owner of the car tries to turn on the engine the alarm sound will player for the player who execute it but it don't work on player A.

I'm currently using open-mp build rc2

**Comment by iamjexcdevvv** [comment]
Shouldn't the alarm be heard by the players who are near it?

**Comment by AmyrAhmady** [comment]
There are issue templates you should use and fill out the forms carefully
Also in your next issue, tell us if you have tested it on SAMP server as well and had your expected behavior.
