### ISSUE TITLE
Is GTA SA DE supported?

### ISSUE THREAD

**Issue by Kingwolf123** [openmultiplayer/open.mp#690]
Is the newer definitive edition supported?

**Comment by NexiusTailer** [comment]
If you have a DE client which meets 0.3.7 or 0.3.DL specs, then yes, ofc.

**Comment by AmyrAhmady** [comment]
This is open.mp server repository

**Comment by Kingwolf123** [comment]
Nobody answered the question. Can i play multiplayer  open.mp with the Definitive Edition?

**Comment by NexiusTailer** [comment]
> Nobody answered the question. Can i play multiplayer open.mp with the Definitive Edition?

Everybody tried to. Mine answer above: if **you have** DE SA-MP client compatible with 0.3.7 or 0.3.DL server, **you can** play on omp server too. If **you don't have**, you **cannot**. As Amir said, there is no any omp client for now, only server. So, probably the answer is "you cannot".

**Comment by AmyrAhmady** [comment]
> Nobody answered the question. Can i play multiplayer open.mp with the Definitive Edition?

Again, this is open.mp server repository and has nothing to do with clients, and if you are not able to find the clients on main website, then no, it's not possible yet, because clients are not released. use common sense.
