### ISSUE TITLE
How I can add more filterscript?

### ISSUE THREAD

**Issue by K4rt0** [openmultiplayer/open.mp#692]
I don't know how to add filterscript, I also tried adding side-scripts in config.json file and then adding filterscripts folder but it still not found. Please help me more :( thanks a lot

**Comment by PerseweratywneImponderabilia** [comment]
You probably used incorrect syntax, path, filename or you haven't compiled your scripts.

Adding this inside the "pawn" block loads the specified scripts just fine for me.
```js
side_scripts": [
  "filterscripts/kylies_barn",
  "filterscripts/attachments",
  "filterscripts/ls_beachside"
]
```

**Comment by K4rt0** [comment]
> Có thể bạn đã sử dụng cú pháp, đường dẫn, tên tệp không chính xác hoặc bạn chưa biên dịch tập lệnh của mình.
> 
> Thêm cái này vào bên trong khối "con tốt" sẽ tải các tập lệnh được chỉ định tốt cho tôi.
> 
> ```js
> side_scripts": [
>   "filterscripts/kylies_barn",
>   "filterscripts/attachments",
>   "filterscripts/ls_beachside"
> ]
> ```

I fixed it, thank you very much:>
