### ISSUE TITLE
Add parameter to Kick function

### ISSUE THREAD

**Issue by plakapenka** [openmultiplayer/open.mp#694]
**Is your feature request related to a problem? Please describe.**
Yes

**Describe the solution you'd like**
Add a parameter to Kick so that you can kick instantly or after sending everything in the queue, as before. An instant kick is needed in 0.1 out of 10 cases. These timers annoy me

**Comment by VictorMacielGhost** [comment]
Just create ur own function to kick bro :chad:

**Comment by pushline** [comment]
> Just create ur own function to kick bro 🇹🇩

I agree with this part, sometimes I need to put a delay of 5 seconds to even show the dialog/message or else it just shows 'server closed the connection' and it's kinda irritating to see it.

**Comment by VictorMacielGhost** [comment]
> > Just create ur own function to kick bro 🇹🇩
> 
> I agree with this part, sometimes I need to put a delay of 5 seconds to even show the dialog/message or else it just shows 'server closed the connection' and it's kinda irritating to see it.

Same, Just
```c
KickEx(playerid, Float:delay, bool:usingSeconds  = false);
{
    if(usingSeconds) delay = (delay * 1000);
    new rounded_delay = floatround(delay);
    SetTimerEx("KickExCallback", false, rounded_delay, "i", playerid);
}

forward KickExCallback(playerid);
public KickExCallback(playerid)
{
    Kick(playerid);
}
```
no?

**Comment by NexiusTailer** [comment]
> Same, Just
> 
> ```c
> KickEx(playerid, Float:delay, bool:usingSeconds  = false);
> {
>     if(usingSeconds) delay = (delay * 1000);
>     new rounded_delay = floatround(delay);
>     SetTimerEx("KickExCallback", false, rounded_delay, "i", playerid);
> }
> 
> forward KickExCallback(playerid);
> public KickExCallback(playerid)
> {
>     Kick(playerid);
> }
> ```
> 
> no?

Making a constant delay is unreliable if it's too small and excessively if it's too big. A better way is to set delay based on player's ping (but also having some upper threshold of its values). The best way would be making this based on raknet checks if all sent messages is delivered to the player or not (and this could be done only built-in).

**Comment by DobbysGamertag** [comment]
Or you can renative it. 

https://github.com/PatrickGTR/gta-open/blob/1d116fa73d585c9a1e2a2c3c2ef6d140118ee880/gamemodes/utils/utils_fix.inc#L58

`Kick` and `Ban` then have a delay

**Comment by plakapenka** [comment]
I'm not asking how I can solve this! Everyone knows this and it's shit

Read the subject and its prefix

**Comment by ksenonadv** [comment]
This is not a bug. 
The current behaviour is intended. 
You can make a function yourself to close the connection after some time.
