### ISSUE TITLE
No Load artconfig

### ISSUE THREAD

**Issue by CrhistopherDiaz** [openmultiplayer/open.mp#701]
The server in windows loads artconfig perfectly but in linux it does not load it

**Comment by CrhistopherDiaz** [comment]
Ubuntu 20.04.6 LTS

**Comment by AmyrAhmady** [comment]
Make sure you are not having case sensitivity issues

**Comment by CrhistopherDiaz** [comment]
> Asegúrese de no tener problemas de distinción entre mayúsculas y minúsculas

friend is well written the server is working in the 0.3dl it loaded the models without problem when I put the open mp the models do not load but in Windows they do

**Comment by CrhistopherDiaz** [comment]
> Make sure you are not having case sensitivity issues

Friend I just tried and for some strange reason in linux it is taking me only the last skin of the txt file the others do not load them I already tried changing the last one below and at the moment it takes it but only the last one
