### ISSUE TITLE
Fcnpc

### ISSUE THREAD

**Issue by CrhistopherDiaz** [openmultiplayer/open.mp#702]
friend I am the project leader of a samp server and I am interested in migrating to open mp but I want to see if you could help me is that on my server we use FCNPC for the kinematics of the registration and missions that we have for the training of the players and I would like to see If you could help me with FCNPC for open mp and thus be able to migrate to open mp

**Comment by eakwarp** [comment]
welcome to those who are waiting and hoping for FCNPC or equivalent. I made the actors walk...

**Comment by AmyrAhmady** [comment]
It is not our responsibility to port people's project to open.mp, at the very least, the maintainer of FCNPC must do it themselves, but they publicly announced they won't
either wait for someone to do it, or don't use it

**Comment by eakwarp** [comment]
> It is not our responsibility to port people's project to open.mp, at the very least, the maintainer of FCNPC must do it themselves, but they publicly announced they won't either wait for someone to do it, or don't use it

the problem is that the openmp(and samp) basic functionality for working with NPCs is currently not enough) if it were enough, no one would have asked for the FCNPC

**Comment by AmyrAhmady** [comment]
I know they are asking for FCNPC and it's needed
still it's not our responsibility, hopefully you can understand that. we already ported many plugins because they were easier to work with.
