### ISSUE TITLE
OnVehicleDamageStatusUpdate bug

### ISSUE THREAD

**Issue by devlucas00** [openmultiplayer/open.mp#706]
the OnVehicleDamageStatusUpdate callback does not work. both with and without hook methods. The vehicle takes damage but the callback is not called. here is how I reproduced this bug:

I created a file named "vehicletest.inc". inside, I used the code below:

`public OnVehicleDamageStatusUpdate(vehicleid, playerid)
{
    printf("OnVehicleDamageStatusUpdate(%i, %i)", vehicleid, playerid);
    return 1;
}

public OnPlayerEnterVehicle(playerid, vehicleid, ispassenger)
{
    printf("OnPlayerEnterVehicle(%i, %i, %i)", playerid, vehicleid, ispassenger);
    return 1;
}

public OnPlayerExitVehicle(playerid, vehicleid)
{
    printf("OnPlayerExitVehicle(%i, %i)", playerid, vehicleid);
    return 1;
}

Console:

OnPlayerEnterVehicle(0, 1, 0)
OnPlayerExitVehicle(0, 1)`

only the other callbacks are called. OnVehicleDamageStatusUpdate is never called. I crash the car into a wall, his health is affected but the callback is not triggered.

I use the latest version of omp.

**Comment by ZantetsukenGT** [comment]
keep in mind the conditions under which this callback may be called, from the samp docs:

```
This callback is called when a vehicle element such as doors, tires, panels, or lights change their damage status.

Note: This does not include vehicle health changes

Example Usage: Prevent tire popping
```

**Comment by AmyrAhmady** [comment]
It's been a very long time and there has been no reply. closing this for now, if anyone still has this issue or anything related, feel free to reply
