### ISSUE TITLE
Synchronization of new created vehicles, weapons, skins

### ISSUE THREAD

**Issue by ghost** [openmultiplayer/open.mp#707]
**I removed the limits on weapons, cars, skins on the client side using the Limit Adjuster plugin from Fastman92, my client's version samp.dll : 0.3.7 R1, server version: open.mp RC2. Using third-party scripts in my GTA, I start samp_debug.exe and I can spawn the created weapons, cars and skins and they work correctly, how to spawn the created skin, car, weapon from the server side? If I used to use the limits patch for samp-server for this, now I don't quite understand what I have to do with the server core, can someone tell me the vector of actions, sorry for my English**

**Comment by unkcs** [comment]
> **I removed the limits on weapons, cars, skins on the client side using the Limit Adjuster plugin from Fastman92, my client's version samp.dll : 0.3.7 R1, server version: open.mp RC2. Using third-party scripts in my GTA, I start samp_debug.exe and I can spawn the created weapons, cars and skins and they work correctly, how to spawn the created skin, car, weapon from the server side? If I used to use the limits patch for samp-server for this, now I don't quite understand what I have to do with the server core, can someone tell me the vector of actions, sorry for my English**


For you to break the SAMP vehicle limits, the Fastman92LimitAdjuster is not enough, you need to break the verification of vehicle model limits in CreateVehicle both on the client and server side.

The other things are probably the same logic.

**Comment by AmyrAhmady** [comment]
Well said above, closing this
