### ISSUE TITLE
PutPlayerInVehicle

### ISSUE THREAD

**Issue by CrhistopherDiaz** [openmultiplayer/open.mp#709]
PutPlayerInVehicle when you use it, it appears as if the user was paused and you don't see him inside the vehicle

**Comment by AmyrAhmady** [comment]
I need an minimal script to reproduce this bug

**Comment by AmyrAhmady** [comment]
It's been a very long time and there has been no reply. closing this for now, if anyone still has this issue or anything related, feel free to reply
