### ISSUE TITLE
Server randomly crashes

### ISSUE THREAD

**Issue by andreev02** [openmultiplayer/open.mp#712]
Crash in a period of 1-2 days. Process just died nothing in log. And then I tried GDB.
Sometimes it's crahing with log where the reason of crash is crashdetect its self (by Y_LESS v4.22)
result:

![photo_2023-09-09_15-09-19](https://github.com/openmultiplayer/open.mp/assets/29811269/40fa4b56-c86a-4665-879d-645a60d67ab0)

**Comment by andreev02** [comment]
crashdetect crash it's self
![image](https://github.com/openmultiplayer/open.mp/assets/29811269/5cdc34c1-48c1-4b77-a974-b427898c7d64)

**Comment by andreev02** [comment]
my log-core
![image](https://github.com/openmultiplayer/open.mp/assets/29811269/020e9456-fb2a-4b39-b6e2-5388f373fbde)

**Comment by AmyrAhmady** [comment]
I am closing this, create a new issue with a proper issue template.

**Comment by BeckzyBoi** [comment]
> crashdetect crash it's self ![image](https://user-images.githubusercontent.com/29811269/266783465-5cdc34c1-48c1-4b77-a974-b427898c7d64.png)

It's a known issue in post RC2 builds. It seems to stem from pickups. There's a similar crash from Vehicles.so too. You did the right thing by opening an issue, which is something I never got round to doing, though your best bet for now would be to revert to the official RC2 release. You always stand a higher chance of experiencing crashes/bugs/other issues when using beta versions.
