### ISSUE TITLE
Server randomly crashes

### ISSUE THREAD

**Issue by andreev02** [openmultiplayer/open.mp#713]
Crash in a period of 1-2 days. Process just died nothing in log. And then I tried GDB.
result:

![photo_2023-09-09_15-09-19](https://github.com/openmultiplayer/open.mp/assets/29811269/40fa4b56-c86a-4665-879d-645a60d67ab0)

**Comment by AmyrAhmady** [comment]
And again, create an issue using on of the issue templates, and fill the form with requested information

select one of these when you click "new issue" button
![IMG_6017](https://github.com/openmultiplayer/open.mp/assets/34688664/34788c57-887d-4ea2-a1d3-9eaa8e93bf6b)

and then give requested information:
![IMG_6018](https://github.com/openmultiplayer/open.mp/assets/34688664/f05f9ce9-056d-456b-b714-4e0f45da2512)
