### ISSUE TITLE
gmx command

### ISSUE THREAD

**Issue by PazzOnee** [openmultiplayer/open.mp#714]
When i restart server by command 'gmx' in console, server send client message for query which is located in OnPlayerDisconnect

I have more queries in OnPlayerDiscconect, but only that server send as message

In samp server this was not problem

**Screenshots and/or logs**
https://streamable.com/ivelxo

**Release version**
RC2

**Comment by Hual** [comment]
Can you post the code?

**Comment by PazzOnee** [comment]
My bad, when player disconnect, server send message near that player with reason code, but i don't have reason 4 in formating message as reason, in reason 4 is case when player disconnect when server restarting
