### ISSUE TITLE
Compile does not show success message when updating YSI-Includes-nightly

### ISSUE THREAD

**Issue by thangtcm** [openmultiplayer/open.mp#715]
![image](https://github.com/openmultiplayer/open.mp/assets/23113822/886ccb4c-29f9-4f25-80a1-c19829142234)

It's really quite annoying when a new version comes out, but there are no specific instructions on integration with the current gamemode. When I tried to update using qawno, it almost always failed to update YSI, and the compiler showed nothing.

**Comment by AmyrAhmady** [comment]
I'm not sure why you're reporting it here, this repository is only for open.mp server, not qawno, not YSI, not omp includes, please create your issue in your related repository

Tip: keep using pawno if you want, you are not forced to use qawno, also you can keep using samp includes. your issue looks like a pawn problem so I suggest asking on our discord in "pawn-help" channel, someone will surely help you.
https://discord.gg/samp
