### ISSUE TITLE
SetSpawnInfo

### ISSUE THREAD

**Issue by nexquery** [openmultiplayer/open.mp#717]
If you try to use a skin added with AddCharModel, you will sometimes spawn with the CJ skin. But this is not always the case. To solve this problem, you need to reuse the SetPlayerSkin function.

![sa-mp-044](https://github.com/openmultiplayer/open.mp/assets/16369564/a70daffc-d82c-4e81-8390-2b164018a7ba)

**Comment by ksenonadv** [comment]
Repro steps?

**Comment by AmyrAhmady** [comment]
Also please share your discord ID so we can contact you and investigate it further

**Comment by nexquery** [comment]
1. Set TogglePlayerSpectating to true when connected to the server.
```c
public OnPlayerConnect(playerid)
{
	TogglePlayerSpectating(playerid, true);
	return 1;
}
```
2. Load the character data after providing the necessary checks.
```c
new fmt[64], hesapid;
mysql_format(gSQL, fmt, sizeof(fmt), "SELECT * FROM karakterler WHERE id = %d;", hesapid);
mysql_tquery(gSQL, fmt, "Karakter_Yukle", "d", playerid);
```
3. Load character data from the callback and use the codes below.
```c
callback::Karakter_Yukle(playerid)
{
	if(cache_num_rows())
	{
		new
			Float:x,
			Float:y,
			Float:z,
			Float:a
		;
		
		cache_get_value_name_float(0, "px", x);
		cache_get_value_name_float(0, "py", y);
		cache_get_value_name_float(0, "pz", z);
		cache_get_value_name_float(0, "pa", a);
		cache_get_value_name_int(0, "skin", Karakter[playerid][karakter_skin]);
		
		TogglePlayerSpectating(playerid, false);
		
		SetSpawnInfo(playerid, NO_TEAM, Karakter[playerid][karakter_skin], x, y, z, a, WEAPON_FIST, 0, WEAPON_FIST, 0, WEAPON_FIST, 0);
		SpawnPlayer(playerid);
	}
	return 1;
}
```

**Comment by Vince0789** [comment]
Toggling spectating off already implicitly spawns the player, an extra call to `SpawnPlayer` should not be necessary. The `SetSpawnInfo` call should probably occur before the player actually spawns, so before spectating is toggled off.

**Comment by PazzOnee** [comment]
@nexquery close 
```
callback::Karakter_Yukle(playerid)
{
	if(cache_num_rows())
	{
		new
			Float:x,
			Float:y,
			Float:z,
			Float:a
		;
		
		cache_get_value_name_float(0, "px", x);
		cache_get_value_name_float(0, "py", y);
		cache_get_value_name_float(0, "pz", z);
		cache_get_value_name_float(0, "pa", a);
		cache_get_value_name_int(0, "skin", Karakter[playerid][karakter_skin]);
		
		SetSpawnInfo(playerid, NO_TEAM, Karakter[playerid][karakter_skin], x, y, z, a, WEAPON_FIST, 0, WEAPON_FIST, 0, WEAPON_FIST, 0);

		TogglePlayerSpectating(playerid, false);
	}
	return 1;
}
```

**Comment by nexquery** [comment]
I edited the codes as you said, I will test it for a while since the problem does not always occur, if it persists I will write again.

**Comment by PazzOnee** [comment]
@nexquery  Close if you done with testing
