### ISSUE TITLE
Core crashes (pickups/gangzones)

### ISSUE THREAD

**Issue by andreev02** [openmultiplayer/open.mp#718]
**Describe the bug**
Server just crashes by it's components (pickups/ganzones) .

**To Reproduce**
Random. Idk.

**Expected behavior**
At first I thought the &IPlayer was nullptr, but then I saw queryExtension<IPlayerGangZoneData>(player);
I check all queryExtensions and see that there is may be nullptr as a result.
![image](https://github.com/openmultiplayer/open.mp/assets/29811269/cccc24a1-a788-46b3-936b-4ceddbe10588)
![image](https://github.com/openmultiplayer/open.mp/assets/29811269/92de8c9d-d1ad-4beb-9e22-1cc1a1e39041)

If I was right some problems may be in gangzones, pickups, dialogs.
![image](https://github.com/openmultiplayer/open.mp/assets/29811269/a6afc953-69cc-4824-85e8-3adbb0a048e6)

**Screenshots and/or logs**
![photo_2023-09-17_13-23-11](https://github.com/openmultiplayer/open.mp/assets/29811269/9290994b-5a77-45db-99dc-fe2ac99ed08f)
![photo_2023-09-17_13-18-45](https://github.com/openmultiplayer/open.mp/assets/29811269/8a9e26db-fd18-41e4-bbcb-6274ebb43d35)

**Release version**
[5746f42d73118b70ceb43edc864897243c766923](https://github.com/openmultiplayer/open.mp/tree/5746f42d73118b70ceb43edc864897243c766923)

**Comment by andreev02** [comment]
![image](https://github.com/openmultiplayer/open.mp/assets/29811269/35e7ae4d-6d31-405e-b16c-6ee6dba72722)

**Comment by andreev02** [comment]
There are alot of places. Check queryExtension
![image](https://github.com/openmultiplayer/open.mp/assets/29811269/4c4edcb6-bdaa-4fca-a9d9-208b8feaa5c5)

**Comment by AmyrAhmady** [comment]
Checking if queried extension is null or not is fine
we are making sure retrieved pointer to our object is not invalid in order to do further actions.

I'd say the parts this check doesn't exist is more problematic, but not sure if that's the cause
thanks for reporting this

**Comment by andreev02** [comment]
> Checking if queried extension is null or not is fine

data == nullptr continue?
![image](https://github.com/openmultiplayer/open.mp/assets/29811269/158acd61-c9f5-4d4c-8093-2465534d67ad)

**Comment by AmyrAhmady** [comment]
Yes, I meant for other pictures you sent, and no, if data is null we are not continuing the execution
I understand the others

**Comment by AmyrAhmady** [comment]
@andreev02 Please try this build and update me with the results

https://github.com/openmultiplayer/open.mp/actions/runs/6217146604

**Comment by andreev02** [comment]
> @andreev02 Please try this build and update me with the results
> 
> https://github.com/openmultiplayer/open.mp/actions/runs/6217146604

Hi. Sorry I can't check it now. Already added checks in forked project. But I found more places to add checks just in case.
![image](https://github.com/openmultiplayer/open.mp/assets/29811269/40a1bbdd-3f32-4460-8547-6ff7eb86a52c)
