### ISSUE TITLE
Core crash after GMX

### ISSUE THREAD

**Issue by andreev02** [openmultiplayer/open.mp#720]
**Describe the bug**
Server random crashes after GMX restart.

**To Reproduce**
Restart server by GMX (no killing process) and just active play and It will crash in ~1 hour. 

**Expected behavior**
We noticed a server crash within a few days after restarts at 5 a.m. After ~1 hour it will crash.
Then we start killall omp-server , ./omp-server to restart and crashes gone.

**Screenshots and/or logs**
![photo_2023-09-09_15-09-19](https://github.com/openmultiplayer/open.mp/assets/29811269/40fa4b56-c86a-4665-879d-645a60d67ab0)

**Release version**
RC2

**Comment by andreev02** [comment]
@AmyrAhmady maybe there is some problems with sampvoice.
https://github.com/AmyrAhmady/sampvoice/issues/13

**Comment by AmyrAhmady** [comment]
Related to sampvoice, closing
