### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by andreev02** [openmultiplayer/open.mp#721]
**Describe the bug**
Just random. Server crahed, started and after 5 minutes again crashed.

**To Reproduce**
...

**Expected behavior**
....

**Screenshots and/or logs**
![image](https://github.com/openmultiplayer/open.mp/assets/29811269/6bf8b034-dea6-445d-b45d-2e0ee2a79242)
![image](https://github.com/openmultiplayer/open.mp/assets/29811269/4d448d80-a934-4fed-a8b7-dd19eddecf01)

**Commit hash in master**
[Put the commit hash or link to the Github Action of the broken build here.](https://github.com/openmultiplayer/open.mp/tree/b442acb1d32cc142a558b6a5fc412da136fae795)

**Comment by andreev02** [comment]
May it be a gamemode problem? Should I run crashdetect? 
(And crash by it's self :^) )

**Comment by AmyrAhmady** [comment]
try building in debug mode (open.mp I mean) then run it with gdb

**Comment by andreev02** [comment]
> try building in debug mode (open.mp I mean) then run it with gdb

in process. after build in debug ??? will show the functions?

**Comment by AmyrAhmady** [comment]
hopefully it should

**Comment by andreev02** [comment]
![image](https://github.com/openmultiplayer/open.mp/assets/29811269/397bfbb6-23f8-4893-bf6b-b8c5fc7553b6)
omp-server: /home/lesha/server/lib/RakNet/Source/RakPeer.cpp:3081: bool RakNet::RakPeer::HandleRPCPacket(const char *, int, RakNet::PlayerID, RakNet::PlayerIndex): Assertion `0' failed.

**Comment by andreev02** [comment]
Maybe it's some problem of my broken hands. I merged from yours upstream without libs maybe. I will refork nightly and send you new result.

**Comment by andreev02** [comment]
There is some problem in sampvoice component when unload. Without it exit fine.
![image](https://github.com/openmultiplayer/open.mp/assets/29811269/eca1d2ef-55ef-4cb2-8224-ee6732b1392d)

**Comment by AmyrAhmady** [comment]
so this issue is related to sampvoice and not open.mp?

**Comment by andreev02** [comment]
Random crash while process. 6 times per day.
![image](https://github.com/openmultiplayer/open.mp/assets/29811269/f9ecc1f0-bac1-405a-a770-bb6a6053a6df)

**Comment by andreev02** [comment]
> so this issue is related to sampvoice and not open.mp?



> There is some problem in sampvoice component when unload. Without it exit fine. ![image](https://user-images.githubusercontent.com/29811269/268988473-eca1d2ef-55ef-4cb2-8224-ee6732b1392d.png)

Idk.

**Comment by AmyrAhmady** [comment]
There's no call stack so we can't really help you, we need to know where HandleRPCPacket call comes from

**Comment by andreev02** [comment]
> There's no call stack so we can't really help you, we need to know where HandleRPCPacket call comes from

Sad :^(
We will downgrade. That crashes have appeared after upgrade to nightly commits. But problem still be actual.

**Comment by AmyrAhmady** [comment]
What if you don't use gdb and only crashdetect?

**Comment by andreev02** [comment]
> only crashdetect

I found something interesting.. I think we started active falling after I ran debug mode.
![image](https://github.com/openmultiplayer/open.mp/assets/29811269/5205b756-4152-4bba-96af-e24960643897)

**Comment by andreev02** [comment]
Some problem in lib or component?

**Comment by andreev02** [comment]
> ![image](https://user-images.githubusercontent.com/29811269/268926056-397bfbb6-23f8-4893-bf6b-b8c5fc7553b6.png) omp-server: /home/lesha/server/lib/RakNet/Source/RakPeer.cpp:3081: bool RakNet::RakPeer::HandleRPCPacket(const char *, int, RakNet::PlayerID, RakNet::PlayerIndex): Assertion `0' failed.

Ok for understanding. That actual when I started debug mode.

the line that complains about
![image](https://github.com/openmultiplayer/open.mp/assets/29811269/6b31f0df-e9f7-465a-9903-4a024b0dd57c)

**Comment by andreev02** [comment]
Just made some brilliant move
![image](https://github.com/openmultiplayer/open.mp/assets/29811269/34ee064a-2a30-4773-b4d4-a43cb810cfea)

We decided to downgrade at https://github.com/openmultiplayer/open.mp/tree/2a78960658935ee45ebeef973972c37f062b762a
Tomorrow I will send you the results with a debag

**Comment by AmyrAhmady** [comment]
If possible, can I have your discord?

**Comment by andreev02** [comment]
> If possible, can I have your discord?

Sure
itandreev02#0997

**Comment by andreev02** [comment]
Today no crashes.

**Comment by AmyrAhmady** [comment]
If tomorrow goes without crash again, we can close this issue

**Comment by AmyrAhmady** [comment]
Closing this as the author also said there's no more crashes on discord and it's safe to close it.
