### ISSUE TITLE
Run time error 10: "Native function failed"

### ISSUE THREAD

**Issue by RiccardoMorreti** [openmultiplayer/open.mp#722]
I use function string_replace

Code:
```c#
string_replace(inputvar[],const searchstring[],const replacestring[],bool:ignorecase=true,bool:replaceall=false)
{
	if(strfind(replacestring,searchstring,ignorecase) != -1) return -1;
	new pos = strfind(inputvar,searchstring,ignorecase);
	if(pos == -1) return 0;
	if(replaceall == true)
	{
		while(strfind(inputvar,searchstring,ignorecase) != -1)
		{
			pos = strfind(inputvar,searchstring,ignorecase);
			strdel(inputvar, pos, pos+strlen(searchstring));
			strins(inputvar, replacestring, pos, strlen(inputvar));
		}
	}
	else
	{
		strdel(inputvar, pos, pos+strlen(searchstring));
		strins(inputvar, replacestring, pos, strlen(inputvar));
	}
	return 1;
}
``` 

String_Replace use strins function for insert a string into another string (wiki).

Before, my server based on samp 0.3.7 server, today i try start my server in open-mp and taken this error in log.txt(Run time error 10: "Native function failed").

**Comment by AmyrAhmady** [comment]
if possible please provide your example of this function usage so we can it quicker

**Comment by RiccardoMorreti** [comment]
```c#
private Dialog.CMDPlugs(playerid, buff[]) {
    if (strfind(buff, "#hid") != -1) {
        new str[32];
        format(str, sizeof(str), "%d", GetPVarInt(playerid, "hEditID"));
        string_replace(buff, "#hid", str, _, true);
    }
}
``` 

```c#
private Dialog.DialogPlugs(playerid, buff[]) {
    if (strfind(buff, "#hdclass") != -1) {
        new houseid = GetPVarInt(playerid, "hEditID")-1;

        new str[32];
        format(str, sizeof(str), "%d", House.Info[houseid][House.hClass]);
        string_replace(buff, "#hdclass", str, _, true);
    }

    if (strfind(buff, "#hdcost") != -1) {
        new houseid = GetPVarInt(playerid, "hEditID")-1;

        new str[32];
        format(str, sizeof(str), "%d", House.Info[houseid][House.hPrice]);
        string_replace(buff, "#hdcost", str, _, true);
    }

    if (strfind(buff, "#hdlock") != -1) {
        new houseid = GetPVarInt(playerid, "hEditID")-1;

        new str[32];
        format(str, sizeof(str), "%d", House.Info[houseid][House.hLock]);
        string_replace(buff, "#hdlock", str, _, true);
    }

    if (strfind(buff, "#hdrtime") != -1) {
        new houseid = GetPVarInt(playerid, "hEditID")-1;

        new str[32];
        format(str, sizeof(str), "%d", House.Info[houseid][House.hRentTime]);
        string_replace(buff, "#hdrtime", str, _, true);
    }
}
```

**Comment by RiccardoMorreti** [comment]
private is define

```c#
#define private stock static
```

Dialog. is define _dialog
```c#
#define Dialog. _dialog
```

**Comment by xunder-matth** [comment]
Show us `string_replace` function.

**Comment by RiccardoMorreti** [comment]
> Show us `string_replace` function.

check first message

**Comment by Vince0789** [comment]
If you intend to modify a string in a function then you should always pass its size along; i.e. add an extra parameter to the function header:
```cs
size = sizeof inputvar
```
Then use that `size` parameters as the `maxlength` in the `strins()` function.

**Comment by RiccardoMorreti** [comment]
> If you intend to modify a string in a function then you should always pass its size along; i.e. add an extra parameter to the function header:
> 
> ```
> size = sizeof inputvar
> ```
> 
> Then use that `size` parameters as the `maxlength` in the `strins()` function.

But if i use this function in samp server, i not have a error...

**Comment by ksenonadv** [comment]
Because SA:MP completely ignores maxlength param.

> > If you intend to modify a string in a function then you should always pass its size along; i.e. add an extra parameter to the function header:
> > ```
> > size = sizeof inputvar
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then use that `size` parameters as the `maxlength` in the `strins()` function.
> 
> But if i use this function in samp server, i not have a error...

**Comment by RiccardoMorreti** [comment]
I dont understand what I need to do to avoid this error anymore, I have the maxlength parameter used in the string_replace function

**Comment by RiccardoMorreti** [comment]
```
strins(inputvar, replacestring, pos, strlen(inputvar));
```

**Comment by ksenonadv** [comment]
> ```
> strins(inputvar, replacestring, pos, strlen(inputvar));
> ```

Maxlength should be the size of the string you want to insert into (inputvar in your case).
Your code should look like this:

```
strins(inputvar, replacestring, pos, sizeof(inputvar));
```

**Comment by Vince0789** [comment]
That will not work (compiler will complain about indeterminate array size). The size needs to be passed down as a parameter through the entire call stack. The function headers of all functions will need to be modified as such:
```c
string_replace(inputvar[], const searchstring[], const replacestring[], bool:ignorecase=true, bool:replaceall=false, maxlength = sizeof inputvar)
private Dialog.CMDPlugs(playerid, buff[], maxlength = sizeof buff)
private Dialog.DialogPlugs(playerid, buff[], maxlength = sizeof buff)
```
And any calls to `strins` or `string_replace` itself in the code above should then include that parameter.

Side note: inventing your own syntax and trying to emulate OOP is poor practice. Especially when asking for help in a thread like this.

**Comment by RiccardoMorreti** [comment]
Its work. Thanks.
