### ISSUE TITLE
After 'GMX' command, server set a default hostname

### ISSUE THREAD

**Issue by RiccardoMorreti** [openmultiplayer/open.mp#723]
I use old method server settings - server.cfg.

My server have custom hostname:
```
echo Executing Server Config...
lanmode 0
rcon_password xxxxxx
maxplayers 100
port 7777
hostname Point-Rp.XX TEST
gamemode0 Point_Rp 1
gamemodetext Point-Rp.XX Russia
filterscripts
announce 1
query 1
weburl www.point-rp.xx
maxnpc 0
onfoot_rate 40
incar_rate 40
weapon_rate 40
stream_distance 300.0
stream_rate 1000
plugins crashdetect.so raktimefix.so streamer.so TOTP.so vectoral.so mysql.so xml.so cef.so redis.so
mapname Russia
language Russian
ackslimit 4500
password xxxxxxXxxxx000
``` 
But after restart with 'GMX' command, server set a default hostname 'open.mp server' - https://i.imgur.com/oh3Vebf.png

**Comment by Zorono** [comment]
1. i think **raktimefix** Plugin is no longer needed (with open.mp server)
2. make sure to set your hostname on config.json the same as yours in server.cfg

and i believe that there should be some workarounds to make some kind of syncing between both configuration files... (@Y-Less @AmyrAhmady)

**Comment by Mortyyka** [comment]
> 1. i think **raktimefix** Plugin is no longer needed (with open.mp server)
> 2. make sure to set your hostname on config.json the same as yours in server.cfg
> 
> and i believe that there should be some workarounds to make some kind of syncing between both configuration files... (@Y-Less @AmyrAhmady)

k they will reply once they have the time bruv chill down

**Comment by RiccardoMorreti** [comment]
> 1. i think **raktimefix** Plugin is no longer needed (with open.mp server)
> 2. make sure to set your hostname on config.json the same as yours in server.cfg
> 
> and i believe that there should be some workarounds to make some kind of syncing between both configuration files... (@Y-Less @AmyrAhmady)

1. Yes, i removed raktimefix plugin from my config file.
2. At the moment, I am not using config.json, in my server folder contains only server.cfg

**Comment by Hual** [comment]
you really decided to skip the issue template for some reason?

**Comment by ksenonadv** [comment]
It should be fixed in latest nightly build.

**Comment by Hual** [comment]
> It should be fixed in latest nightly build.

if only we knew which version this was reported in, like the version field the template has

**Comment by AmyrAhmady** [comment]
This is fixed in latest build, wait for an official release and use nightly
