### ISSUE TITLE
Player stuck in walking animation upon spawn

### ISSUE THREAD

**Issue by BluevsRedTDM** [openmultiplayer/open.mp#728]
**Describe the bug**
Upon spawning, the player is stuck in a walking animation until they cancel it by clicking or jumping. The avatar walks forward a few steps, then teleports back to the first frame of the animation and this repeats forever in perpetuity. The camera can be freely rotated while this animation occurs. This occurs on the first time they spawn after logging in and does not occur again until they close the game and log back in.

**To Reproduce**
1. Type Password
2. Click Spawn Button

**Expected behavior**
Upon spawning, the character should be standing still.

**Screenshots and/or logs**
https://www.youtube.com/watch?v=_rSjCLF3l14

**Release version**
RC2

https://github.com/openmultiplayer/open.mp/assets/146032684/bc7ad6e1-98eb-49b2-af2f-fe78acc1df68

**Comment by AmyrAhmady** [comment]
Can you try removing Fixes component and rechecking the issue?

**Comment by BluevsRedTDM** [comment]
I'm not sure what you mean by that. Can you elaborate?

**Comment by AmyrAhmady** [comment]
there's a component in components folder, called Fixes. remove that and recheck please

**Comment by BluevsRedTDM** [comment]
Fantastic. That worked and the issue is no longer occurring. Thank you.
