### ISSUE TITLE
Ban, banip bug

### ISSUE THREAD

**Issue by PazzOnee** [openmultiplayer/open.mp#730]
***RELEASE 2 AND NIGHLT BUG***

**Describe the bug**
When you ban or banip player with Ban(), BanEx() functions, that didn't work, player not will be banned, and they can again connect to the server (reloadbans done), but when you do it with /rcon, banip will work fine, /rcon ban, /rcon banip, and when you ban player (ip) using /rcon ban ID, other player with same ip will not be dissconected, but they can't rejoin server

samp.ban have all permisions to write/read, and in samp.ban file was written and deleted things, but not working...

**To Reproduce**
Try command to ban https://pastebin.com/U60BF6hh , and test it
Then try with rcon ingame (/rcon login, /rcon ban, /rcon banip, /rcon unbanip), and test it

**Comment by AmyrAhmady** [comment]
open.mp uses bans.json, not samp.ban

**Comment by PazzOnee** [comment]
@AmyrAhmady Yes, i meant bans.json

**Comment by PazzOnee** [comment]
@AmyrAhmady I tested it and i confim it working, but not working for localhost incoming connection, if that's okay, then ok, else reopen issue
