### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by PazzOnee** [openmultiplayer/open.mp#732]
**RELEASE AND NIGHTLY BUG**

**Describe the bug**
If you do this code (kick player in first i think 5 second when connecting) player not will be kicked from server, only spamming lost connection from server, and reconnect, and repeating only, if you put delay to 10000ms (10 seconds) or more that will be fine, player will be kicked, but 10 second is too much...

```
public OnPlayerConnect(playerid)
{
    SetTimerEx("DelayKick", 3000, false, "d", playerid);
    return 1;
}

forward DelayKick(playerid);
public DelayKick(playerid)
{
    Kick(playerid;
    return 1;
}
```

you are probably wondering why I am doing this, when a player connects, a query is sent to the base if the player exists in the ban table, if there is, the server will kick him and send him a return message, but there is this problem because when the delay is less than 5 seconds, it will just reconnect the player again and again ( https://prnt.sc/dKYDMZBlzPYB )

**Comment by Mortyyka** [comment]
Basically the same as #704

**Comment by AmyrAhmady** [comment]
Duplicate, closing
