### ISSUE TITLE
IsValidPlayerGangZone is an empty function that always returns true

### ISSUE THREAD

**Issue by shierru** [openmultiplayer/open.mp#743]
I found that the **IsValidPlayerGangZone** function is currently a simple void that always returns true.

[_Line in gangzone component_](https://github.com/openmultiplayer/open.mp/blob/a32e732a1fb881a7850ce7ee051023540199cbfc/Server/Components/Pawn/Scripting/GangZone/PlayerNatives.cpp#L77)

**Comment by AmyrAhmady** [comment]
It only returns true if `IPlayer` arg and `IPlayerGangZone` arg are successfully retrieved from integer player ID and gangzone ID sent from pawn
if given IDs are not valid, then function automatically returns false and never enters native declaration scope (the one you see and call empty)

If you need more information of how it works, you can ask me on discord

**Comment by shierru** [comment]
For some reason I forgot about it when creating the issue, even though I know it very well.
