### ISSUE TITLE
float variable ,,bug,,

### ISSUE THREAD

**Issue by PazzOnee** [openmultiplayer/open.mp#746]
**Describe the bug**
Float variables not showing correct decimal sometime
In this case second and eight parameter not correct showing

**To Reproduce**
Do code
`main() { 
	printf("[0]%.2f, [1]%.2f, [2]%.2f, [3]%.2f, [4]%.2f, [5]%.2f, [6]%.2f, [7]%.2f", 1.10, 1.15, 1.20, 1.25, 1.74, 1.70, 1.80, 2.50);
}`

if you do %f instead of %.2f you will see that [1] is 1.14999 and [6] 1.7999

**Expected behavior**
output now is "[0]1.10, [1]1.14, [2]1.20, [3]1.25, [4]1.74, [5]1.70, [6]1.79, [7]2.50"
output need to be "[0]1.10, [1]1.15, [2]1.20, [3]1.25, [4]1.74, [5]1.70, [6]1.80, [7]2.50"

**Release version**
SAMP version, RC2, and nighly build

**Comment by AmyrAhmady** [comment]
This is not a bug, it is an expected behavior of floating point numbers
read & use this https://www.h-schmidt.net/FloatConverter/IEEE754.html
