### ISSUE TITLE
warning 202: number of arguments does not match definition

### ISSUE THREAD

**Issue by PazzOnee** [openmultiplayer/open.mp#748]
**Native function have parameter for more argumetns, but when i put more arguments i got warning**

```
native bool:SendClientMessage(playerid, colour, const format[], OPEN_MP_TAGS:...); //no warning
SendClientMessage(playerid, -1, "Text %s %s", "test" , "test2");  //no warning

native bool:PlayerTextDrawSetString(playerid, PlayerText:textid, const format[], OPEN_MP_TAGS:...); //yes warning
PlayerTextDrawSetString(playerid, PlayerText:textid, "Test %s %s", "test", "test2"); //yes warning
```
there are many more such functions that give warnings and have the possibility of additional arguments

**Comment by AmyrAhmady** [comment]
This is for server software only, you have pawn compiler warnings
use this repository to report your issues
https://github.com/openmultiplayer/omp-stdlib
