### ISSUE TITLE
How to build nightly open.mp in Debian 11?

### ISSUE THREAD

**Issue by RiccardoMorreti** [openmultiplayer/open.mp#750]
I need FAQ for build nightly open.mp in Debian 11, please.

**Comment by AmyrAhmady** [comment]
We provide latest builds already (latest commit from master), you can download them here:
https://github.com/openmultiplayer/open.mp/actions/runs/6600366962#artifacts

If you still insist on building it your own, check our workflows
https://github.com/openmultiplayer/open.mp/blob/fe7760055329e601ca4bbd718b4c474361ab55e8/.github/workflows/build.yml#L123

which they use our docker files, and you can find them here:
https://github.com/openmultiplayer/open.mp/tree/master/docker
