### ISSUE TITLE
After exiting, the players remain on the server

### ISSUE THREAD

**Issue by RiccardoMorreti** [openmultiplayer/open.mp#754]
I installed nightly build open.mp server, after that as soon as a player leaves the game, he remains standing still in the AFK.

The Kick function does not save the situation

https://imgur.com/a/3YhJ0GJ

**Comment by RiccardoMorreti** [comment]
video: https://imgur.com/a/ilJi4Or

**Comment by AmyrAhmady** [comment]
Duplicate of #688 , but  I'm keeping this one open to use it as a reminder
Next time please don't create an issue when it's already reported

**Comment by NexiusTailer** [comment]
Is it still relevant?
