### ISSUE TITLE
SetPickupVirtualWorld not updating pickup model & position

### ISSUE THREAD

**Issue by BeckzyBoi** [openmultiplayer/open.mp#755]
**Describe the bug**
If using SetPickupModel or SetPickupPos with update parameter as false then using SetPickupVirtualWorld, the pickup model and position isn't updated.

**To Reproduce**

SetPickupModel(pickupid, newmodel, false); // false to not yet update the pickup
SetPickupPos(pickupid, newx , newy, newz, false); // false to not yet update the pickup
SetPickupVirtualWorld(pickupid, newworld);  // the previously changed model and position should be updated too, but they aren't

**Expected behavior**
SetPickupVirtualWorld should update the model and position too if previously changed & not updated

**Commit hash in master**
Well it still happens in latest nightly, however I believe (I'm sorry if I'm wrong) it started here: https://github.com/openmultiplayer/open.mp/actions/runs/5318350518?pr=684

**Comment by AmyrAhmady** [comment]
Fixed next build.
