### ISSUE TITLE
Feature Request: RemoveWater (sandandreas)

### ISSUE THREAD

**Issue by coool9** [openmultiplayer/open.mp#758]
**Is your feature request related to a problem? Please describe.**
Not really a problem I have but it would be coool to remove the oceans.

**Describe the solution you'd like**
I want to remove the water. A part of it Or all of it.

**Describe alternatives you've considered**
None

**Additional context**
We all know that one screenshot.... SandAndreas

P.S I used the feature request template so don't blame me if it's not up to mark.

**Comment by AmyrAhmady** [comment]
We're taking server related issues as of now, I'm tagging this with client but I also have to close it.

**Comment by coool9** [comment]
I also have another very similar issue. Shall I create it and you just add the client label and close it?

**Comment by AmyrAhmady** [comment]
Just add it to this issue

**Comment by coool9** [comment]
> Just add it to this issue

CreateWater

**Comment by coool9** [comment]
@AmyrAhmady kindly transfer this issue to open.mp/launcher

**Comment by AmyrAhmady** [comment]
it has nothing to do with launcher, it's very client specific.
