### ISSUE TITLE
Can u write tutorial convert gamemode samp to open mp ?

### ISSUE THREAD

**Issue by thangtcm** [openmultiplayer/open.mp#764]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by adib-yg** [comment]
I already wrote a tutorial, hope it helps.
https://github.com/adib-yg/openmp-server-installation#openmp-server-installation

**Comment by thangtcm** [comment]
yeah, thanks, and i hope openmp add (try catch)
