### ISSUE TITLE
FloatSin and FloatCos

### ISSUE THREAD

**Issue by BitFros7y** [openmultiplayer/open.mp#773]
**Describe the bug**
Sinus and CoSinus float functions are kind of bugged. If angle values are less then 0 or greater or equal to 360, functions return 0.

**To Reproduce**
 Just pass angle as negative number and unexpected stuff starts happening

**Expected behavior**
Function should handle angles that go to negative values. 

**Screenshots and/or logs**
N/A

**Release version**
Release v1.1.0.2612

PS: In samp server default behaviour is to handle negative angles and those greater then 360degrees.

**Comment by Vince0789** [comment]
Cannot reproduce. Show the code you are using. Make sure you specifying `degrees` for `anglemode`.

**Comment by BitFros7y** [comment]
Tried on empty script with newest server and it works fine. My Bad, closing issue.
