### ISSUE TITLE
Player gets stuck/freezes when using PutPlayerInVehicle

### ISSUE THREAD

**Issue by adib-yg** [openmultiplayer/open.mp#781]
**Describe the bug**
This issue is related to other clients. (mobile)
Player is stuck into the vehicle when using the `PutPlayerInVehicle` function and the player cannot even exit the vehicle or move the camera or vehicle. It's like the player is frozen.
This does not happen on the SA-MP server.

**To Reproduce**
1. Use `PutPlayerInVehicle`

**Screenshots and/or logs**
<img src="https://i.ibb.co/BTfrW4g/Screenshot.jpg" alt="Screenshot">

<img src="https://i.ibb.co/zRMmbhQ/screenshot.jpg" alt="screenshot">

**Release version**
omp v1.1.0.2612

**Comment by AmyrAhmady** [comment]
Does this still happen? can you try with and without Fixes component

**Comment by adib-yg** [comment]
I just tested, it doesn't happen anymore in the latest release (v1.2.0.2670)
