### ISSUE TITLE
bugs - suggestion

### ISSUE THREAD

**Issue by MyASQL** [openmultiplayer/open.mp#785]
add support for plugins/libraries at least rewrite some of them. 

- solutions to errors in the console.

**Comment by Hual** [comment]
what

**Comment by Zorono** [comment]
please can you explain what do you mean??

**Comment by pushline** [comment]
![image](https://github.com/openmultiplayer/open.mp/assets/36933632/2e424eea-f21b-4d18-921a-3c23f9c85565)
guy is trolling
