### ISSUE TITLE
Health and armor recovery when damaging

### ISSUE THREAD

**Issue by PazzOnee** [openmultiplayer/open.mp#789]
**Describe the bug**
When use weapon-config.inc and omp-server this happening >
https://streamable.com/ah7gul
On link you can see video where i shooting player with weapon, and a little percent of health, armor is giving back to player

On samp server player normaly lose health and armour when get damaged

**To Reproduce**
1. Just run omp server with weapon-config and pawnraknet included
2. Enable ANTI CBUG in weapon config include
3. Then damage player with guns, like on video
4. Healths and Armour will giving back

**Expected behavior**
Not to giving healh and armour back, just normaly give damage and lost health

**Screenshots and/or logs**
[If applicable, add screenshots and/or log output to help explain your problem.](https://streamable.com/ah7gul)

**Commit hash in master**
I didn't test in RC2
https://github.com/openmultiplayer/open.mp/actions/runs/6825213368

**Comment by AmyrAhmady** [comment]
I don't think this is related to open.mp, create an issue in weapon-config repository
