### ISSUE TITLE
Sorting files under `models` folder in server directory

### ISSUE THREAD

**Issue by Jedrzej94** [openmultiplayer/open.mp#794]
There's an `artwork.models_path` setting in `config.json`

Can you make it somehow read subdirectories of that specified path in `models_path`  as well?

Right now it only reads the root folder. The entire folder is a mess when too many models and characters are coming down in.

**Comment by NexiusTailer** [comment]
> Right now it only reads the root folder. The entire folder is a mess when too many models and characters are coming down in.

Just like components folder tbh

**Comment by AmyrAhmady** [comment]
This is a breaking change and it won't happen
it is always better to just define your path in adding script native so you always know where your model ID X is coming from, instead of having to guess the path of the file 10 folders deep in actual models folder
