### ISSUE TITLE
Hardware information for ban functions

### ISSUE THREAD

**Issue by sicariodll** [openmultiplayer/open.mp#810]
**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
There should be functions to get users hardware information like Mac id, CPU id, HDD id and etc. IP bans are weak and can be easily passed with a modem restart. CI isn't too functional cause it's not unique and someone innocent can be banned.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by NexiusTailer** [comment]
It cannot be done without client modification; Even if it will be (a client modification, and then this done), it's pretty easy to bypass it so don't flatter yourself in advance.

**Comment by sicariodll** [comment]
@NexiusTailer I don't flatter myself, it's just an idea. No need to be rude like that. :)

**Comment by Hual** [comment]
I'm pretty sure it was just a bad translation for "don't get your hopes up"
