### ISSUE TITLE
Problem with Kick()

### ISSUE THREAD

**Issue by Hidacska** [openmultiplayer/open.mp#816]
**Describe the bug**
We've encountered regarding player stays online after they are kicked using the RCON kick or the Kick() function.

When a player is kicked through either method, the kick process runs correctly, and the player sees the "Server closed the connection" message as expected. However, despite being kicked, other players still perceive the kicked player as online. In this state, the player appears to be AFK with a large ping.

**To Reproduce**
Use "rcon kick" or Kick() function on someone.

**Expected behavior**
The server must close the connection really.

**Screenshots and/or logs**
![kép](https://github.com/openmultiplayer/open.mp/assets/45129801/fdb57808-65d1-402d-a4ee-5e0e792891e9)

**Release version**
v1.1.0.2612

**Comment by PazzOnee** [comment]
@Hidacska Test now with latest build https://github.com/openmultiplayer/open.mp/actions/runs/8556095715

**Comment by AmyrAhmady** [comment]
Fixed in latest nightly, closing
