### ISSUE TITLE
Server crashed due to unknown error after  ± 3/4 hours started.

### ISSUE THREAD

**Issue by alansyahdwi** [openmultiplayer/open.mp#824]
The server randomly crashed after approximately 3/4 hours of starting. i used omp-v1.1.0.2612.

**minidump files:**
[omp_minidump.dmp](https://github.com/openmultiplayer/open.mp/files/13804626/omp_minidump.dmp)

**log.txt:**
![Screenshot 2024-01-01 201149](https://github.com/openmultiplayer/open.mp/assets/63584768/293927b1-1bd9-415d-b1aa-510bc6531424)

**Comment by PazzOnee** [comment]
add -d3 frag in build config and load crashdetect plugin

**Comment by alansyahdwi** [comment]
> add -d3 frag in build config and load crashdetect plugin

i have
![image](https://github.com/openmultiplayer/open.mp/assets/63584768/c9262410-3ca0-4546-98e3-c9c305819a81)

**Comment by PazzOnee** [comment]
@alansyahdwi let us output from server log when server crashed

**Comment by alansyahdwi** [comment]
> @alansyahdwi let us output from server log when server crashed

here is the full log:
[log (4).txt](https://github.com/openmultiplayer/open.mp/files/13804748/log.4.txt)

**Comment by PazzOnee** [comment]
@alansyahdwi use pastebin.com or sometnig like that and send

**Comment by alansyahdwi** [comment]
> @alansyahdwi use pastebin.com or sometnig like that and send

https://pastebin.com/iNKJ6M8R

i can't send u full log.txt on pastebin, cause there is a limit 512kb on pastebin

**Comment by Hual** [comment]
Can you try the latest nightly to see if it's fixed?

**Comment by alansyahdwi** [comment]
> Can you try the latest nightly to see if it's fixed?

where can i get the latest nightly version?

**Comment by PazzOnee** [comment]
@alansyahdwi 
https://github.com/openmultiplayer/open.mp/actions

sort by 'Build' and download latest 'master' >

https://github.com/openmultiplayer/open.mp/actions/runs/7371678064

**Comment by alansyahdwi** [comment]
> @alansyahdwi https://github.com/openmultiplayer/open.mp/actions
> 
> sort by 'Build' and download latest 'master' >
> 
> https://github.com/openmultiplayer/open.mp/actions/runs/7371678064

ok thankyou lemme try.

**Comment by alansyahdwi** [comment]
seems like the problem is solved using the nightly version, thankyou!
