### ISSUE TITLE
New function to find out if some component/plugin is loaded.

### ISSUE THREAD

**Issue by shierru** [openmultiplayer/open.mp#826]
# Description

While working on one script I came up with the idea to give users the choice to use the implementation of some costly functions or to use an analog of the same function implementation only in the form of **component/plugin**.

And I wondered, how can I tell if a **component/plugin** is loaded? 

## _The first variation_, that came to mind is to use [GetConsoleVarAsString](https://github.com/openmultiplayer/omp-stdlib/blob/085dfb13eb615955d89057c4564201b70786fee6/omp_core.inc#L905). Simply find out what exactly the user has in **config.json** and build a foundation on that. 

But this method has some problems:
1. You can't find out if any components are loaded, you can find out if certain legacy_plugins are loaded, but not components, because they are loaded automatically and don't need to be declared in **config.json**.

2. By the first problem it became clear that we can only find out **legacy_plugins**, but there is another problem: we can't find out if the plugin was loaded successfully or if it was loaded with some error.

## _The second variation_, is related to implementation on the side of a separate component (but this will cause additional dependencies and is not very suitable), or implementation on the side of **open.mp**.

Now let's get to the point of the proposal, is it possible to implement a new function similar to [GetConsoleVarAsString](https://github.com/openmultiplayer/omp-stdlib/blob/085dfb13eb615955d89057c4564201b70786fee6/omp_core.inc#L905) function and other similar ones, which would be able to tell if some **component/plugin** is loaded or not. Perhaps it would be possible to find out whether it is loaded with an error or not, but this is nothing more than a passive task, which is unlikely to be useful in practice.

# 

Such functionality would be useful for **filterscripts**, so that in some cases developers could allow the user to use certain functionality without depending on **component/plugin** or use the full power of **Pawn** without depending on **component/plugin**.

Thank you for your attention! 
Perhaps I wrote some nonsense or it is already realized, but still I wanted to put the idea I put it, now what will be decided by fate :)

**Comment by shierru** [comment]
From a discussion in **Discord** with @Hual revealed a pitfall.

If the amx script will use any unregistered function, an error will occur on load. This complicates the fact that a **Pawn script** can use a certain kind of implementation (either in a component/plugin or on the **Pawn** side).

**Comment by AmyrAhmady** [comment]
Closing this due to not being able to come up with a solution for it with pawn's limitations
