### ISSUE TITLE
Some functions are missing

### ISSUE THREAD

**Issue by adib-yg** [openmultiplayer/open.mp#834]
**Describe the bug**

These functions are missing:

`HideObjectForPlayer`
`ShowObjectForPlayer`
`IsObjectHiddenForPlayer`
`HideNewObjectsForPlayer`
`NewObjectsHiddenForPlayer`

But they are implemented in omp-stdlib.

![image](https://github.com/openmultiplayer/open.mp/assets/92677767/c6f412e9-77a6-4ca5-a3fe-330691661fb3)

**Release version**
omp v1.1.0.2612

**Comment by NexiusTailer** [comment]
omp-stdlib was recently updated and all non-implemented natives were finally removed from there, so this issue in probably no longer relevant. Adding all those functions as natives in the server itself is more about "porting the rest YSF stuff" (and such issues are already created).
