### ISSUE TITLE
We need IsPlayerPaused

### ISSUE THREAD

**Issue by JH3Y50N** [openmultiplayer/open.mp#837]
**Is your feature request related to a problem? Please describe.**
Add IsPlayerPaused(playerid), i wanna use Open MP server but i cannot.. because YSF don't start..

**Describe the solution you'd like**
IsPlayerPaused function

**Describe alternatives you've considered**
None

**Additional context**
I need this function to my anticheat.
![image](https://github.com/openmultiplayer/open.mp/assets/29031972/6587b9db-b7e4-462b-8340-8ade1b2c7175)
![image](https://github.com/openmultiplayer/open.mp/assets/29031972/24f3a0e0-c4ed-42f5-8b70-86e94585e540)

**Comment by J0nathan550** [comment]
Legacy Plugins you should put inside of the plugins folder and define it inside of the config.json.

Not all of the plugins can go into components folder. Be aware.

**Comment by NexiusTailer** [comment]
I'd like to see a function which won't be inaccurate for half of use cases. IsPlayerPaused **is** by default, because it uses delay (how much time a player did not sent any sync) to detect AFK. This delay is usually set to 1500 or 2000 ms. What if I need to detect it faster? Maybe I need longer delay? So, if making anything like this function built-in, it should be at least with configurable delay, something like `IsPlayerPaused(playerid, delay = 1500)`. This way I could manually set the time if I constantly get false positives on afk when it's actually not (player is lagging) or false negatives on afk when it's actually in, but the function still report it's not.

**Comment by J0nathan550** [comment]
> I'd like to see a function which won't be inaccurate for half of use cases. IsPlayerPaused **is** by default, because it uses delay (how much time a player did not sent any sync) to detect AFK. This delay is usually set to 1500 or 2000 ms. What if I need to detect it faster? Maybe I need longer delay? So, if making anything like this function built-in, it should be at least with configurable delay, something like `IsPlayerPaused(playerid, delay = 1500)`. This way I could manually set the time if I constantly get false positives on afk when it's actually not (player is lagging) or false negatives on afk when it's actually in, but the function still report it's not.

So in later versions we will see this function by default?

**Comment by JH3Y50N** [comment]
> I'd like to see a function which won't be inaccurate for half of use cases. IsPlayerPaused **is** by default, because it uses delay (how much time a player did not sent any sync) to detect AFK. This delay is usually set to 1500 or 2000 ms. What if I need to detect it faster? Maybe I need longer delay? So, if making anything like this function built-in, it should be at least with configurable delay, something like `IsPlayerPaused(playerid, delay = 1500)`. This way I could manually set the time if I constantly get false positives on afk when it's actually not (player is lagging) or false negatives on afk when it's actually in, but the function still report it's not.

In the case of YSF I believe that it does not use time, but rather the connection status, when you go afk an hourglass appears next to your Nick, it is possible to detect this..

**Comment by NexiusTailer** [comment]
> In the case of YSF I believe that it does not use time, but rather the connection status, when you go afk an hourglass appears next to your Nick, it is possible to detect this..

No it's not related to connection status because it won't change in this case.
Seems it's [a basic time check](https://github.com/IS4Code/YSF/blob/50a861667370a07aa2c52b3a2fd03c0db566e1c1/src/CPlayerData.cpp#L240) as expected.

> So in later versions we will see this function by default?

Tbh I don't see the point to make it not on pawn side, but it's just imho and I'm not an omp dev

**Comment by J0nathan550** [comment]
> > In the case of YSF I believe that it does not use time, but rather the connection status, when you go afk an hourglass appears next to your Nick, it is possible to detect this..
> 
> No it's not related to connection status because it won't change in this case. Seems it's [a basic time check](https://github.com/IS4Code/YSF/blob/50a861667370a07aa2c52b3a2fd03c0db566e1c1/src/CPlayerData.cpp#L240) as expected.
> 
> > So in later versions we will see this function by default?
> 
> Tbh I don't see the point to make it not on pawn side, but it's just imho and I'm not an omp dev

Anyway there is plugin already for that, but still would be great to see the function like this, it can be helpful sometimes.

**Comment by AmyrAhmady** [comment]
`IsPlayerPaused` is entirely depended on time. You can make the exact function in your gamemode using `OnPlayerUpdate` and a time check, there's no need to add an unreliable function to open.mp

**Comment by JH3Y50N** [comment]
Then remove the console message on the server startup

![image](https://github.com/openmultiplayer/open.mp/assets/29031972/4a142870-be93-4943-bbc8-4b8f062c678f)

**Comment by AmyrAhmady** [comment]
I'm sorry that we didn't clarify we will only add functions that are reliable and actually work :)

**Comment by NexiusTailer** [comment]
The only thing which really wrong with it now and should be changed is YSF & fixes definitions inside omp includes (like it's fully interchangeable stuff, but it's not).
