### ISSUE TITLE
IsPlayerCuffed returns false when cuffed players crouch

### ISSUE THREAD

**Issue by BeckzyBoi** [openmultiplayer/open.mp#841]
**Describe the bug**
IsPlayerCuffed returns false on cuffed players if they crouch, making it impossible to detect if crouched players are cuffed (GetPlayerSpecialAction will return crouched).

**To Reproduce**
1. Set your special action to cuffed
2. Crouch
3. IsPlayerCuffed will return false

**Expected behavior**
IsPlayerCuffed should be true when used on a crouching cuffed player?

**Screenshots and/or logs**
Not applicable/necessary. The issue is self explanatory 

**Release version**
v1.1.0.2612 and v1.1.0.2668, but presumably all versions since IsPlayerCuffed was added?

**Comment by Hual** [comment]
This is caused by GetPlayerSpecialAction returning ducked instead of cuffed so it's a SAMP issue

**Comment by BeckzyBoi** [comment]
> This is caused by GetPlayerSpecialAction returning ducked instead of cuffed so it's a SAMP issue

IsPlayerCuffed was added because passengers can be cuffed and GetPlayerSpecialAction returns 0 on cuffed passengers. With this logic, crouching players can also be cuffed - it's merely another instance of GetPlayerSpecialAction not returning cuffed, so IsPlayerCuffed should probably work in this case too?

![Screenshot_20240118-144355~2](https://github.com/openmultiplayer/open.mp/assets/34369978/bf3d86c4-d94e-48f2-ac12-47210ee68d7c)

**Comment by xunder-matth** [comment]
This native shouldn't be implemented in open.mp server code if it's not reliable.

**Comment by NexiusTailer** [comment]
I think it worth being in server because IsPlayerCuffed as well as IsPlayerInDriveByMode are natives which provide access to these flags from other sources (inside passenger sync) comparing with special actions and camera modes (which was used by scripters to get this data before). It can just be renamed to something like "IsPlayerCuffedAsPassenger" or "IsPlayerCuffedInVehicle".

**Comment by Hual** [comment]
> > This is caused by GetPlayerSpecialAction returning ducked instead of cuffed so it's a SAMP issue
> 
> IsPlayerCuffed was added because passengers can be cuffed and GetPlayerSpecialAction returns 0 on cuffed passengers. With this logic, crouching players can also be cuffed - it's merely another instance of GetPlayerSpecialAction not returning cuffed, so IsPlayerCuffed should probably work in this case too?
> 
> ![Screenshot_20240118-144355~2](https://private-user-images.githubusercontent.com/34369978/297778444-bf3d86c4-d94e-48f2-ac12-47210ee68d7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MjcyNzcsIm5iZiI6MTcwNTgyNjk3NywicGF0aCI6Ii8zNDM2OTk3OC8yOTc3Nzg0NDQtYmYzZDg2YzQtZDk0ZS00OGYyLWFjMTItNDcyMTBlZTY4ZDdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDA4NDkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzMGIxMzI1Mzc2ZDBmZDc5ZjZlYWM1MmM5YjhiMmVjZGVjOTZjMzJlMzk5Mjg5YTA5NzQ1NWZhYzFkZjU1YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TrXi0b8e--IbH4yhw5uycVWi9t-2yzLFkk3zRX8WFvs)

The thing is samp sends the special action in client sync so there's nothing that can be done from the server side

**Comment by BeckzyBoi** [comment]
> > > This is caused by GetPlayerSpecialAction returning ducked instead of cuffed so it's a SAMP issue
> > 
> > 
> > IsPlayerCuffed was added because passengers can be cuffed and GetPlayerSpecialAction returns 0 on cuffed passengers. With this logic, crouching players can also be cuffed - it's merely another instance of GetPlayerSpecialAction not returning cuffed, so IsPlayerCuffed should probably work in this case too?
> > ![Screenshot_20240118-144355~2](https://private-user-images.githubusercontent.com/34369978/297778444-bf3d86c4-d94e-48f2-ac12-47210ee68d7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MjcyNzcsIm5iZiI6MTcwNTgyNjk3NywicGF0aCI6Ii8zNDM2OTk3OC8yOTc3Nzg0NDQtYmYzZDg2YzQtZDk0ZS00OGYyLWFjMTItNDcyMTBlZTY4ZDdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDA4NDkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzMGIxMzI1Mzc2ZDBmZDc5ZjZlYWM1MmM5YjhiMmVjZGVjOTZjMzJlMzk5Mjg5YTA5NzQ1NWZhYzFkZjU1YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TrXi0b8e--IbH4yhw5uycVWi9t-2yzLFkk3zRX8WFvs)
> 
> The thing is samp sends the special action in client sync so there's nothing that can be done from the server side

I assumed that with GetPlayerSpecialAction returning 0 in vehicles and IsPlayerCuffed being true that it'd be possible to make it work when GetPlayerSpecialAction is ducking too. If I'm wrong then my bad. It'd be nice for the IsPlayerCuffed to work on ducking players too but I guess I can use a variable to achieve that, and reset the variable upon applying a new animation/action and upon death too.

**Comment by AmyrAhmady** [comment]
It's not really possible to reliably do that, so we just rely on actual data we receive from players
