### ISSUE TITLE
Legacy key: supplied, using.

### ISSUE THREAD

**Issue by Giyzooo** [openmultiplayer/open.mp#842]
**Describe the bug**
to be removed, or to stop giving that warning in the console.

**To Reproduce**
1. only if you have that rule in the database.

photo: 
![lsmadkndf](https://github.com/openmultiplayer/open.mp/assets/155848751/918396af-44bf-486f-b120-1615d2a68fe7)

**Comment by Mortyyka** [comment]
This isn't a bug and also shouldn't be removed, this is just a simple warning message, and it states
``This won't affect the server's behaviour``

You're also probably hosting your server on a local environment, thus this showing up.

**Comment by ksenonadv** [comment]
It was fixed in latest nightly build.
