### ISSUE TITLE
KeyListener plugin doesn't work, but it is said that it should work. 

### ISSUE THREAD

**Issue by J0nathan550** [openmultiplayer/open.mp#844]
[](url)Hello, I have an quite interesting bug with KeyListener plugin by the CyberMor.
In the OPEN.MP documentation in `awesome` section it is defined that KeyListener plugin can be used if to activate it. 
I did it, and at the end retrieved this console error.

Error in legacy plugin:
![Screenshot_1](https://github.com/openmultiplayer/open.mp/assets/88881607/65672f3b-e7f3-4f4b-8d0c-e08a20d0c3bf)

Error in components (if to try to load in components):
![Screenshot_3](https://github.com/openmultiplayer/open.mp/assets/88881607/4f6c4b43-860a-48b4-ad65-684dacff2f36)

I tried to move the keylistener to the components folder, but it failed. 
Can you explain what to in this case? And if there is nothing I can do with that, why it is described in official docs?!

Screenshot of recommending `awesome` plugin:
![Screenshot_2](https://github.com/openmultiplayer/open.mp/assets/88881607/34bb6159-1b1f-41f5-b03c-4e40cd2c8dc0)

[Plugin KeyListener](https://github.com/CyberMor/keylistener)
[Official docs](https://www.open.mp/en/docs/awesome)

**Comment by AmyrAhmady** [comment]
The list you are referring to is not dedicated to open.mp only. It was created before open.mp release, as an awesome tools and libraries made in community, whether compatible with samp or not

**Comment by J0nathan550** [comment]
> The list you are referring to is not dedicated to open.mp only. It was created before open.mp release, as an awesome tools and libraries made in community, whether compatible with samp or not

Will there be any workaround or I should report issue to CyberMor?
