### ISSUE TITLE
malware detection

### ISSUE THREAD

**Issue by Giyzooo** [openmultiplayer/open.mp#845]
[scan archive win86](https://www.virustotal.com/gui/file/6c370bda541699c171614aa19a35253ab8ee6f1cd6a56385024ddfda727f0e29/detection)

@AmyrAhmady

**Comment by NermanLegacy** [comment]
Very known false positive, just search up the "virus" name and you will be greeted with a lot of examples that happened to other applications.

**Comment by AmyrAhmady** [comment]
only antivirus that flagged it as malware is MaxSecure, which is not even a good one, and very untrustworthy 
https://www.reddit.com/r/antivirus/comments/rz7gzn/maxsecure_the_antivirus_i_dont_recommend/
https://www.reddit.com/r/antivirus/comments/qo9vus/is_this_safe_and_false_positive_from_virustotal/

Either way, it's an open source project, you can build the files yourself if you don't trust us, all of our projects are open source and transparent to public.

You can scan any random file you want and it's high chance MaxSecure is going to report a false-positive malware detection. try samp-npc.exe
