### ISSUE TITLE
Add an empty "plugins" folder in future release packages

### ISSUE THREAD

**Issue by adib-yg** [openmultiplayer/open.mp#850]
Currently there are "filterscripts", "scriptfiles" and "models" folders except "plugins" folder.
I don't know why you guys forgot or is it on purpose, It doesn't really matter anyway.

**Comment by FreddieCrew** [comment]
I guess that's on purpose, as they surely want to incentivize server developers to use plugins that use the open.mp SDK and encourage plugin developers to convert their plugins to the open.mp SDK or create new ones using the open.mp SDK.
Anyway, I don't think the plugin folder is necessary, as you can easily create it with just a few clicks.

**Comment by AmyrAhmady** [comment]
As @FreddieCrew somewhat explained, plugins folder is considered legacy just for people to use samp plugins
