### ISSUE TITLE
When i close pc and go sleep next day i use open.mp its open first time the single player must leave it and rejoin to get in samp this bug happened with me too many times my game is clean

### ISSUE THREAD

**Issue by MuhabFarghaly** [openmultiplayer/open.mp#851]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots and/or logs**
If applicable, add screenshots and/or log output to help explain your problem.

**Release version**
Put the release version of the broken build here.

**Comment by AmyrAhmady** [comment]
Pleas use https://github.com/openmultiplayer/launcher ti create issues related to open.mp launcher
