### ISSUE TITLE
Functions HideVehicle, ShowVehicle, IsVehicleHidden not found

### ISSUE THREAD

**Issue by Locky0** [openmultiplayer/open.mp#853]
https://www.open.mp/docs/scripting/functions/IsVehicleHidden
https://www.open.mp/docs/scripting/functions/HideVehicle
https://www.open.mp/docs/scripting/functions/ShowVehicle

When implementing any of these functions in the script, the server does not recognize them.
v1.2.0.2670

[Error] Function not registered: ShowVehicle
[Error] Function not registered: HideVehicle

**Comment by FreddieCrew** [comment]
Which version of open.mp are you currently using? Try using the [nightly build](https://github.com/openmultiplayer/open.mp/actions/runs/7689936785) and see if it works.

**Comment by pushline** [comment]
> Which version of open.mp are you currently using? Try using the [nightly build](https://github.com/openmultiplayer/open.mp/actions/runs/7689936785) and see if it works.

He stated in the issue that it was 'v1.2.0.2670'

**Comment by Locky0** [comment]
I also tested it on version 1.2.0.2673, without it working.

**Comment by Locky0** [comment]
In the includes, these functions are as forward, I found it strange because they are functions and not callbacks...

**Comment by adib-yg** [comment]
These functions have not been added to the vehicle component yet, probably in future releases.
So they just forwarded them for now.

**Comment by adib-yg** [comment]
[Missed (but important) YSF natives #636](https://github.com/openmultiplayer/open.mp/issues/636)

**Comment by AmyrAhmady** [comment]
closing this in favor of #636
