### ISSUE TITLE
Addition of JSON Variable for Discord Image Link in Open.mp Launcher

### ISSUE THREAD

**Issue by J0nathan550** [openmultiplayer/open.mp#854]
**Feature Request: Addition of JSON Variable for Image Link in Open.mp Launcher**

My feature request is to incorporate a JSON variable that can store a link to an image. This image will later be parsed by Open.mp.

### What it Will Do?

Upon entering the game, Open.mp will retrieve the image from the `config.json` file and append it to the Large Image Key variable. This image will then be displayed as the image of the project you are currently playing.

It feels boring to constantly see the Open.mp logo in the launcher. However, I believe that implementing this feature, which allows for the correct parsing of online images (similar to how Discord server links work in the launcher), would greatly enhance the user experience.

This addition provides developers with a fantastic opportunity to promote their projects through Discord RPC status. Now, instead of just displaying the status of where you're playing, the launcher can showcase a visually appealing image associated with the project.

I do belive, that Discord RPC can support the image link parsing, because myself I used Discord RPC a lot in my .NET projects, and I think that it's not hard to do. 

See the: [Free Spotify](https://github.com/J0nathan550/Free-Spotify)

**Comment by AmyrAhmady** [comment]
It is already planned. thanks for creating this issue, but please it create a new one in launcher repository

**Comment by J0nathan550** [comment]
> It is already planned. thanks for creating this issue, but please it create a new one in launcher repository

Sorry, didn't know it was duplicate. And I was unsure if this goes to open.mp or to launcher itself, since open.mp is a server, and config.json is only for server. So don't know how to connect them in one 😄
