### ISSUE TITLE
Chinese encoding problem!!!

### ISSUE THREAD

**Issue by iLuXing** [openmultiplayer/open.mp#859]
**Describe the bug**
Chinese will not display correctly anywhere with openmp.
not only config.json and gamemode.pwn
my sublime-text encoding is "utf-8"

**To Reproduce**
`
<<gamemode.pwn>>
#include <open.mp>
main() {
    print("你好，世界！");
}
`
<<config.json>>
`
"language": "简体中文",
"name": "中文游戏",
`
![1](https://github.com/openmultiplayer/open.mp/assets/3232110/d92238cf-2b4b-47d6-b867-6792e21e142d)
![2](https://github.com/openmultiplayer/open.mp/assets/3232110/eca56949-d981-4d01-8cb2-ccc5a95b16f8)
![3](https://github.com/openmultiplayer/open.mp/assets/3232110/56a95a03-bba8-4d46-b432-fa18ee076f05)
![4](https://github.com/openmultiplayer/open.mp/assets/3232110/be8e88d8-ad6d-4457-9425-e59adef82de2)

**Comment by iLuXing** [comment]
![5](https://github.com/openmultiplayer/open.mp/assets/3232110/02389469-4421-4201-ac3f-5421e2c95802)

**Comment by qq1258626799** [comment]
config.json调中文服务器名确实在旧版客户端里会乱码。

地图可以用gbk格式的，我是这样解决的..

**Comment by AmyrAhmady** [comment]
Use server.cfg if you can't use utf8 (config.json is utf8, because json is, there's no way around it)
samp launcher does not support utf8, but open.mp launcher does (and other encodings)
