### ISSUE TITLE
Open mp client - server password issue

### ISSUE THREAD

**Issue by 0xDizzle** [openmultiplayer/open.mp#861]
When players try to connect to a server that was previously passworded (only if they actually connected to it using a password before) it will keep saying "incorrect password" for them or they'll be stuck in a "connecting to..." loop, even though the server password was removed.

**To reproduce the bug:**
set a server password in config.json
open the server
connect to it using the password set earlier
/q and close the server
remove the password from config.json
open the server and try to connect
it will say incorrect password or will keep trying to connect to no avail

**Comment by AmyrAhmady** [comment]
Please create it in https://github.com/openmultiplayer/launcher repository
