### ISSUE TITLE
Weapons do not appear in interiors even though they are allowed in the config

### ISSUE THREAD

**Issue by JH3Y50N** [openmultiplayer/open.mp#864]
**Describe the bug**
When you enter an interior the weapons disappear, when you leave they return, the configuration is as allowed but it doesn't work

allow_interior_weapons = true in the config and still happens

**To Reproduce**
Just enter in an interior

**Expected behavior**

**Screenshots and/or logs**
![image](https://github.com/openmultiplayer/open.mp/assets/29031972/a996bc4a-675e-42c8-9494-9606bec4c5c1)

**Release version**
lasted

**Comment by BigETI** [comment]
Was it a wrong report, or why did you close this issue?

**Comment by BeckzyBoi** [comment]
He had AllowInteriorWeapons(0) in OnGameModeInit
