### ISSUE TITLE
Vehicle models ID limit

### ISSUE THREAD

**Issue by Rams25** [openmultiplayer/open.mp#868]
Hi, I have edit every 212 & 611 model id limit to 213 & 612 but my vehicle doesn't spawn.

![image](https://github.com/openmultiplayer/open.mp/assets/60780565/9addc3fd-44b8-4113-9ca8-c328fe5fc3ca)

`cmd:veh(playerid, params[])
{
    new vehid = CreateVehicle(612, 1806.0824,-1857.9149,13.4141,274.2064, 0, 0, -1, 0);
    Notify(playerid, "%d", vehid);
    printf("id : %d", vehid);
    new Float:vPos[3];
    GetVehiclePos(vehid, vPos[0], vPos[1], vPos[2]);
    Notify(playerid, "pos : %f %f %f | %f %f %f", 1806.0824,-1857.9149,13.4141, vPos[0], vPos[1], vPos[2]);
    PutPlayerInVehicle(playerid, vehid, 0);
    return true;
}`

`[2024-02-14T12:45:17+0100] [Info] id : 2`
![image](https://github.com/openmultiplayer/open.mp/assets/60780565/f970e37a-a752-477f-beb3-53eebe5e9444)

Can u help me please ?
Thanks u very much !

**Comment by AmyrAhmady** [comment]
client side issue, not open.mp
