### ISSUE TITLE
TogglePlayerSpectating on&off will cause client not work after "F4"

### ISSUE THREAD

**Issue by iLuXing** [openmultiplayer/open.mp#875]
I want player back to class select interface when player spwaned. so i make this code.
`

CMD:test(playerid){
    ForceClassSelection(playerid);
    TogglePlayerSpectating(playerid, true);
    TogglePlayerSpectating(playerid, false);
}

`
TogglePlayerSpectating on&off will cause client not work after "F4" or ForceClassSelection.
it will not back to class selection view and cant do anything only when /quit

![微信图片_20240222144905](https://github.com/openmultiplayer/open.mp/assets/3232110/cf45f5b3-fd3f-4f78-8973-52dbe1bfc6b3)

**Comment by J0nathan550** [comment]
Not sure, what is your problem. But with the latest stable release of the open.mp this issue doesn't replicate. Try updating server.

**Comment by J0nathan550** [comment]
Also, keep in mind that ClassSelection is useful only when you have `AddPlayerClass` added inside. If you have none or just one this will not work.

**Comment by J0nathan550** [comment]
https://youtu.be/GKpdkpCCYqE

**Comment by iLuXing** [comment]
Thank you. I'll try it again.

**Comment by DevD4v3** [comment]
This problem still occurs, even with the latest version of open.mp. 
It is difficult to reproduce it, because sometimes this problem appears and sometimes it does not.

@iLuXing Were you able to solve it?
