### ISSUE TITLE
X64 Server compile.

### ISSUE THREAD

**Issue by J0nathan550** [openmultiplayer/open.mp#876]
I don't know if it's possible, but what if there is an ability to make x64 bit Open.MP server? It may fix ton of issues. And also expand server limits. Also the entire server will depend on entire RAM of the computer instead of limit of 4GB.

I know that's a lot of fuss to make x64 bit server. But in reality would it fix a lot of issues?

**Comment by AmyrAhmady** [comment]
It is already available in https://github.com/openmultiplayer/open.mp/actions and supposedly works
