### ISSUE TITLE
Default Interior Shops API.

### ISSUE THREAD

**Issue by J0nathan550** [openmultiplayer/open.mp#877]
Hello! I saw that GTA SA SAMP and Open.MP itself in default server can enable the default pickups of shops where you can enter inside and walk around. Besides that in gun shops of ammunation you can find a thing that you can buy guns inside of default SAMP server, if you have enough money.

My question is and maybe feature, is to make ability to have a control over those kind of shops, and possibly add them yourself. With ability to change prices or simply execute events or functions when certain item in shop was bought.

If you don't know what I'm talking about here is the video.

https://youtu.be/3erP6P31p8s

**Comment by NexiusTailer** [comment]
You cannot modify them anyhow changing only the serverside, it is mostly about client changes, so it requires sa-mp client modifications to do it.

Anyway, you can re-make them from scratch on the server even now and even on samp server.
[This is an example of how to do it](https://sampforum.blast.hk/showthread.php?tid=600609).
