### ISSUE TITLE
Improve trailer validation

### ISSUE THREAD

**Issue by NexiusTailer** [openmultiplayer/open.mp#879]
We already have some validations for trailer when player sends trailer sync, but what about incar/driver sync, where trailerid is also sent to be finally put into functions like `GetVehicleTrailer` or `IsTrailerAttachedToVehicle`? This is a piece of code from incar/driver sync:

https://github.com/openmultiplayer/open.mp/blob/62a2fa95b36b73640a5b4bb330a1663d6d50adc9/Server/Source/player_pool.hpp#L1162-L1170

it can be improved at least checking if reported trailerid is streamed in for this player

**Comment by ksenonadv** [comment]
As you can see, we're not using the id from received in driver packet. Instead vehicle.getTrailer() is used to fetch the data obtained from trailer sync which is checking multiple things, including if trailer is streamed.
https://github.com/openmultiplayer/open.mp/blob/62a2fa95b36b73640a5b4bb330a1663d6d50adc9/Server/Components/Vehicles/vehicle.cpp#L310

**Comment by NexiusTailer** [comment]
Oh, ok. I didn't get where the vehicle.getTrailer() fills with new trailerid and where in resets if player stopped sending a trailer in driver sync.

**Comment by NexiusTailer** [comment]
Seems now I found the place from where `getTailer()` receives all the values when they changed:
https://github.com/openmultiplayer/open.mp/blob/62a2fa95b36b73640a5b4bb330a1663d6d50adc9/Server/Components/Vehicles/vehicle.cpp#L219-L251

And since it is obtained from **driver** sync, not trailer, a check if the trailer is streamed in still needed, I suppose:
```pawn
// Got a new one that we didn't know about.
trailer = static_cast<Vehicle*>(pool->get(vehicleSync.TrailerID));
if (trailer) // <- Probably here
{
	trailer->cab = this;
}
```
