### ISSUE TITLE
GetVehicleOccupant and GetVehicleMaxPassengers are missing from includes

### ISSUE THREAD

**Issue by BeckzyBoi** [openmultiplayer/open.mp#880]
**Describe the bug**
GetVehicleOccupant and GetVehicleMaxPassengers are missing from the include files (they work just fine if defined in script)

**Expected behavior**
To be included (probably in omp_vehicles.inc?) as follows:

`native GetVehicleOccupant(vehicle, seat);`
`native GetVehicleMaxPassengers(model);`

**Release version**
1.2.0.2670

**Comment by adib-yg** [comment]
Added in https://github.com/openmultiplayer/omp-stdlib/pull/33 but not yet merged.

**Comment by Y-Less** [comment]
Merged via openmultiplayer/omp-stdlib#38.  33 did have them, but still has some bits under discussion.
