### ISSUE TITLE
messageslimit bug

### ISSUE THREAD

**Issue by 0724-Tsu** [openmultiplayer/open.mp#882]
If server closed connection for player with reason 'messageslimit' in log.txt - player-'phantom' stay on server, but physical player is banned. Player-phantom have ping, skin, all information about him and occupies a slot.

To Reproduce this - reach the 'messageslimit' limit.

**Comment by akosd127** [comment]
#801

**Comment by AmyrAhmady** [comment]
should work in latest nightly build now, closing

https://github.com/openmultiplayer/open.mp/actions/runs/8556095715#artifacts
