### ISSUE TITLE
Train carriage bug/crash

### ISSUE THREAD

**Issue by dimmyi** [openmultiplayer/open.mp#894]
It appears that the client automatically adds carriages with IDs in exact sequence, for example, if the main train is ID 365, the client (internally) will create carriages with IDs 366,367 and 368.

In openMP, carriages are only stored in available slots, and not necessarily in sequence, for example:

Slots:
365 - *Ocuppied*
366 -
367 -
368 - *Ocuppied*
369 -
370 -

openMP will create the main train in slot 366, and the carriages in slots 367, 369 and 370, that is, it is not in sequence and the ID that will be created for the client will be occupied by another vehicle or a non-existent one.

In SA-MP I noticed that when you create a train, it will look for 4 available slots in sequence, so in the example above, sa-mp will create the main train in slot: 369 and the carriages in slots 370, 371 and 372

How to reproduce the bug:
https://www.youtube.com/watch?v=RADMmGx1LyQ

_In the video you can see that the client internally removed a vehicle that was already created (NRG-500) and caused a warning._ 

How to fix?
Apparently, just do the same as SA-MP and only create the train if you find 4 available slots in sequence.

**Comment by AmyrAhmady** [comment]
This happens in samp server as well, the problem is within samp client, not server side
https://streamable.com/dn3mbv
