### ISSUE TITLE
Couldn't announce legacy network to open.mp list

### ISSUE THREAD

**Issue by ZeeRik** [openmultiplayer/open.mp#895]
I am using a Linux server and getting errors:

> [2024-03-15 03:36:12] [2024-03-15T03:36:12+0300] [Info] Couldn't announce legacy network to open.mp list.
> [2024-03-15 03:36:12] [2024-03-15T03:36:12+0300] [Info]         [Server Error] Status: 406
> [2024-03-15 03:36:12] [2024-03-15T03:36:12+0300] [Info]         [Server Error] Message: {"error":"failed to query server: socket read timed out"}
> [2024-03-15 03:36:12] [2024-03-15T03:36:12+0300] [Info] This won't affect the server's behaviour.

The server does not appear in the "Internet" tab.

Starting open.mp server (1.2.0.2670) from commit 41ebf182bf73dc9cb11841bfe6b0179ba31f9dd5

**Comment by AmyrAhmady** [comment]
> This won't affect the server's behaviour.

Also for any reason, your server is not accessible from our website
You can add your server to https://open.mp/servers manually
