### ISSUE TITLE
Audio Stream

### ISSUE THREAD

**Issue by Cioobanu** [openmultiplayer/open.mp#903]
When you quickly stop an audio stream or start an audio stream quickly in a script, even more than one in a row, there is a chance that the previous one will not stop, even though the stop is entered in front of it, and the other one will start next to it. I don't know if this is a client error or a server-side error, but if we switch the audio streams slowly, this will not happen, but I feel that many players will use our TextDrawos radio to quickly switch music.
Is it possible to find a solution for this? Or what kind of error would that be exactly?

**Comment by Wannacry-ops** [comment]
Opus

**Comment by AmyrAhmady** [comment]
client problem
