### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by PazzOnee** [openmultiplayer/open.mp#909]
**Describe the bug**
Server crashing when player connects, disconnects

OS used: Windows 10 PRO 22H2 07-Dec-19, build 19045.4170

**To Reproduce**
Just start server,  and connect, disconnect players/bots, and kick them from console (kick ID)

**Expected behavior**
Not to crash

**Screenshots and/or logs**
Here is server log, and dump file output
https://pastebin.com/6KbXAsrv > server log
[omp_minidump.dmp](https://github.com/openmultiplayer/open.mp/files/14843944/omp_minidump.dmp) >> dmp

**Commit hash in master**
https://github.com/openmultiplayer/open.mp/actions/runs/8513613245

[open.mp-win-Win32-v1.2.0.2670-24-gfcdc806b](https://github.com/openmultiplayer/open.mp/actions/runs/8513613245/artifacts/1375575508)

**Comment by PazzOnee** [comment]
This is output from ubuntu 20.04, but dump file not exist and not creating, all files have full permissions

https://pastebin.com/a04yD1gp

Version used > [open.mp-linux-x86-v1.2.0.2670-24-gfcdc806b](https://github.com/openmultiplayer/open.mp/actions/runs/8513613245/artifacts/1375575507)

**Comment by Sef69** [comment]
Same, from my experience, server crash when player reconnect or crash

**Comment by PazzOnee** [comment]
@AmyrAhmady Working properly in latest master https://github.com/openmultiplayer/open.mp/actions/runs/8556095715

Closed
