### ISSUE TITLE
Open.MP server does not properly disconnect the player when the player exceeds the ackslimit

### ISSUE THREAD

**Issue by AlejandroMHA** [openmultiplayer/open.mp#918]
**Describe the bug**
When the player exceeds the acks limit, and passes a few seconds, the player loses connection with the server **(Screenshot 1)**. But the player is still displayed as connected in the player list in the SAMP launcher **(Screenshot 2)** and within the server (when using the TAB key).
No player disconnection message is displayed in the server logs **(Screenshot 3)**.

And when the player tries to connect to the server again. The player receives the message that they connected to the server without the server showing them the skin selector or the actions that should be shown to the user after connecting to the server (for example a login dialog) **(Screenshot 4)**.
And no user connection message is shown in the logs **(Screenshot 5)**.

**To Reproduce**
_1. Exceed the acks limit. To disconnect the player:_
For testing, you can set the acks limit to a low number (less than 100), to cause the player to disconnect for exceeding the acks limit at the time the player connects.

_2. Check the list of players in the SA-MP launcher or within the server using another player with the TAB key:_
You should see that the player is still shown as connected to the server, but is actually disconnected.

_3. Connect to the server again:_
The server only shows the message "Connected. Joining the game..." without showing the skin selector.

**Expected behavior**
The player must properly disconnect from the server when exceeding the acks limit.

**Screenshots and/or logs**
Screenshot 1:
![image](https://github.com/openmultiplayer/open.mp/assets/50057438/5122adcb-e884-4e65-88e9-7e17b269df39)
Screenshot 2:
![image](https://github.com/openmultiplayer/open.mp/assets/50057438/1cee83c4-44eb-4140-a916-26eefee343f1)
Screenshot 3:
![image](https://github.com/openmultiplayer/open.mp/assets/50057438/101610a7-782f-4824-a09c-872b03748ac8)
Screenshot 4:
![image](https://github.com/openmultiplayer/open.mp/assets/50057438/c272d424-81a8-4de6-a804-7c18941fca2a)
Screenshot 5:
![image](https://github.com/openmultiplayer/open.mp/assets/50057438/2109b8f5-6f1f-403f-9033-8e337ed3ab60)

**Release version**
omp server 1.2.0.2670

**Comment by AmyrAhmady** [comment]
Already fixed in master, use nightly builds if you want the fix.

https://github.com/openmultiplayer/open.mp/actions/runs/8702914340#artifacts
