### ISSUE TITLE
Announce: make HTTP client errors human readable

### ISSUE THREAD

**Issue by Vince0789** [openmultiplayer/open.mp#927]
Should a HTTP client error be encountered while trying to announce, the resulting status code should be made human readable. Note that these **error** status codes are distinctly different from HTTP **response** status codes. A HTTP client error "13" ostensibly means "connection timeout" but this is by no means made clear and is not documented anywhere.

It appears open.mp is using the httplib.h library, which provides the following method to make HTTP client errors human readable:

https://github.com/yhirose/cpp-httplib/blob/388a8c007c96857b36901f3801f6572362ad6b17/httplib.h#L2085

**Comment by AmyrAhmady** [comment]
Fixed in #928
