### ISSUE TITLE
OpenSSL error

### ISSUE THREAD

**Issue by lPauI** [openmultiplayer/open.mp#934]
**Describe the bug**
When I try to start omp-server it gives me an error.

**To Reproduce**
Just start omp-server the dyn ssl build on debian 12.

**Expected behavior**
I try to start the server and I get an "No such file or directory" error.

**Screenshots and/or logs**
./omp-server: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

**Release version**
v1.2.0.2670

**Comment by karthigenius** [comment]
> **Describe the bug** When I try to start omp-server it gives me an error.
> 
> **To Reproduce** Just start omp-server the dyn ssl build on debian 12.
> 
> **Expected behavior** I try to start the server and I get an "No such file or directory" error.
> 
> **Screenshots and/or logs** ./omp-server: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
> 
> **Release version** v1.2.0.2670

Use 32 bit version,
As it happened to me in 64 bit version
This could be due to running a 64 bit version in 32 bit OS

**Comment by Vince0789** [comment]
Debian 12 comes with libssl3, which is entirely the reason why there is a static build (using libssl1.1) available for download.

**Comment by lPauI** [comment]
> Debian 12 comes with libssl3, which is entirely the reason why there is a static build (using libssl1.1) available for download.

Yes but if I use the static build, when I run the server I get this warning:

"Running static OpenSSL build - plugins that use OpenSSL might crash (discord-connector, pawn-requests). It's recommended to use the dynssl build."

**Comment by karthigenius** [comment]
> > Debian 12 comes with libssl3, which is entirely the reason why there is a static build (using libssl1.1) available for download.
> 
> Yes but if I use the static build, when I run the server I get this warning:
> 
> "Running static OpenSSL build - plugins that use OpenSSL might crash (discord-connector, pawn-requests). It's recommended to use the dynssl build."

Did you tried that 32 bit version of dynssl.?

**Comment by lPauI** [comment]
> > > Debian 12 comes with libssl3, which is entirely the reason why there is a static build (using libssl1.1) available for download.
> > 
> > 
> > Yes but if I use the static build, when I run the server I get this warning:
> > "Running static OpenSSL build - plugins that use OpenSSL might crash (discord-connector, pawn-requests). It's recommended to use the dynssl build."
> 
> Did you tried that 32 bit version of dynssl.?

Only 32 bit version of dynssl is released now by open.mp, so the only version that I used by now it's 32 bit.

**Comment by karthigenius** [comment]
> > > > Debian 12 comes with libssl3, which is entirely the reason why there is a static build (using libssl1.1) available for download.
> > > 
> > > 
> > > Yes but if I use the static build, when I run the server I get this warning:
> > > "Running static OpenSSL build - plugins that use OpenSSL might crash (discord-connector, pawn-requests). It's recommended to use the dynssl build."
> > 
> > Did you tried that 32 bit version of dynssl.?
> 
> Only 32 bit version of dynssl is released now by open.mp, so the only version that I used by now it's 32 bit.

Its consists of two bit version of every dynssl release you could check the nightly link of it

[32 Bit](https://github.com/openmultiplayer/open.mp/actions/runs/9721039075/artifacts/1650653518)
[64 Bit](https://github.com/openmultiplayer/open.mp/actions/runs/9721039075/artifacts/1650653515)

**Comment by karthigenius** [comment]
> > > > Debian 12 comes with libssl3, which is entirely the reason why there is a static build (using libssl1.1) available for download.
> > > 
> > > 
> > > Yes but if I use the static build, when I run the server I get this warning:
> > > "Running static OpenSSL build - plugins that use OpenSSL might crash (discord-connector, pawn-requests). It's recommended to use the dynssl build."
> > 
> > Did you tried that 32 bit version of dynssl.?
> 
> Only 32 bit version of dynssl is released now by open.mp, so the only version that I used by now it's 32 bit.

My bad, I didn't see the version, it was fixed up in the nightly version

**Comment by lPauI** [comment]
> > > > > Debian 12 comes with libssl3, which is entirely the reason why there is a static build (using libssl1.1) available for download.
> > > > 
> > > > 
> > > > Yes but if I use the static build, when I run the server I get this warning:
> > > > "Running static OpenSSL build - plugins that use OpenSSL might crash (discord-connector, pawn-requests). It's recommended to use the dynssl build."
> > > 
> > > 
> > > Did you tried that 32 bit version of dynssl.?
> > 
> > 
> > Only 32 bit version of dynssl is released now by open.mp, so the only version that I used by now it's 32 bit.
> 
> My bad, I didn't see the version, it was fixed up in the nightly version

Where is the nightly version?

**Comment by karthigenius** [comment]
> > > > > > Debian 12 comes with libssl3, which is entirely the reason why there is a static build (using libssl1.1) available for download.
> > > > > 
> > > > > 
> > > > > Yes but if I use the static build, when I run the server I get this warning:
> > > > > "Running static OpenSSL build - plugins that use OpenSSL might crash (discord-connector, pawn-requests). It's recommended to use the dynssl build."
> > > > 
> > > > 
> > > > Did you tried that 32 bit version of dynssl.?
> > > 
> > > 
> > > Only 32 bit version of dynssl is released now by open.mp, so the only version that I used by now it's 32 bit.
> > 
> > My bad, I didn't see the version, it was fixed up in the nightly version
> 
> Where is the nightly version?

https://github.com/openmultiplayer/open.mp/actions/runs/9721039075

**Comment by lPauI** [comment]
> > > > > > > Debian 12 comes with libssl3, which is entirely the reason why there is a static build (using libssl1.1) available for download.
> > > > > > 
> > > > > > 
> > > > > > Yes but if I use the static build, when I run the server I get this warning:
> > > > > > "Running static OpenSSL build - plugins that use OpenSSL might crash (discord-connector, pawn-requests). It's recommended to use the dynssl build."
> > > > > 
> > > > > 
> > > > > Did you tried that 32 bit version of dynssl.?
> > > > 
> > > > 
> > > > Only 32 bit version of dynssl is released now by open.mp, so the only version that I used by now it's 32 bit.
> > > 
> > > 
> > > My bad, I didn't see the version, it was fixed up in the nightly version
> > 
> > 
> > Where is the nightly version?
> 
> https://github.com/openmultiplayer/open.mp/actions/runs/9721039075

Give me a link where I can download the nightly version.

**Comment by lPauI** [comment]
> > > > > > > Debian 12 comes with libssl3, which is entirely the reason why there is a static build (using libssl1.1) available for download.
> > > > > > 
> > > > > > 
> > > > > > Yes but if I use the static build, when I run the server I get this warning:
> > > > > > "Running static OpenSSL build - plugins that use OpenSSL might crash (discord-connector, pawn-requests). It's recommended to use the dynssl build."
> > > > > 
> > > > > 
> > > > > Did you tried that 32 bit version of dynssl.?
> > > > 
> > > > 
> > > > Only 32 bit version of dynssl is released now by open.mp, so the only version that I used by now it's 32 bit.
> > > 
> > > 
> > > My bad, I didn't see the version, it was fixed up in the nightly version
> > 
> > 
> > Where is the nightly version?
> 
> https://github.com/openmultiplayer/open.mp/actions/runs/9721039075

Even in the nightly version I get the same error.

./omp-server: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

**Comment by AmyrAhmady** [comment]
@lPauI 
> "Running static OpenSSL build - plugins that use OpenSSL might crash (discord-connector, pawn-requests). It's recommended to use the dynssl build."

If you are not using any of those plugins, then ignore this warning, it clearly says it might crash because of those two and nothing else

> Even in the nightly version I get the same error.
> 
> ./omp-server: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory  


This means you are using dynssl version, in order to use dynssl you MUST have libssl 1.1 installed on your linux, use google to learn how to install it

**Comment by lPauI** [comment]
> @lPauI
> 
> > "Running static OpenSSL build - plugins that use OpenSSL might crash (discord-connector, pawn-requests). It's recommended to use the dynssl build."
> 
> If you are not using any of those plugins, then ignore this warning, it clearly says it might crash because of those two and nothing else
> 
> > Even in the nightly version I get the same error.
> > ./omp-server: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
> 
> This means you are using dynssl version, in order to use dynssl you MUST have libssl 1.1 installed on your linux, use google to learn how to install it

Actually I use discord-connector so I need to use the dynssl version. How can I install libssl 1.1 on debian 12?
I think libssl1.1 is deprecated and I can't install it on modern linux.

**Comment by Parquez** [comment]
how to setup dynssl build for (discord-connector, pawn-request) ...

**Comment by AmyrAhmady** [comment]
@Parquez 

![Image](https://github.com/user-attachments/assets/ab7bd9a0-84c2-482a-ba19-8d31f464fb72)

**Comment by Parquez** [comment]
wheres this link bro

**Comment by Parquez** [comment]
i found now thank you bro

**Comment by Parquez** [comment]
hey amyr
amyr

**Comment by Parquez** [comment]
i want to talk you for samp discord plugins presence

**Comment by itsneufox** [comment]
Amir,

We've Been Trying To Reach You About Your Car's Extended Warranty

Please Contact Us!
