### ISSUE TITLE
Linux server hangs reading legacy config (server.cfg)

### ISSUE THREAD

**Issue by NexiusTailer** [openmultiplayer/open.mp#938]
For some reason, this is only related to linux version of omp server, windows server is fine in this matter.
The problem is when you have more than one space symbol in one of the places here:
```
gamemode0  name  1
```
between the `gamemode0`, `name` or its next argument

**To Reproduce**
Put up linux omp server and have any server.cfg in the folder, adding something similar to the line above in `gamemode0` section.

**Screenshots and/or logs**
The last line in the log file is `[Info] Legacy Network started on [ip]`, just like when it's started with no issues, but the server is stuck and gamemode won't load.

**Release version**
[Latest available](https://github.com/openmultiplayer/open.mp/releases/tag/v1.2.0.2670)

**Comment by AmyrAhmady** [comment]
Fixed in nightly, available officially in next release.
