### ISSUE TITLE
Linux doesn't has bans.json

### ISSUE THREAD

**Issue by AthallahDzaki** [openmultiplayer/open.mp#948]
**Describe the bug**
In release section Linux doesn't has bans.json likely in windows package.

**To Reproduce**
...

**Expected behavior**
Linux package include bans.json to..

**Screenshots and/or logs**
1. Windows
![image](https://github.com/user-attachments/assets/700974ff-7ffc-473c-b930-a986e0db1a5e)

2. Linux
![image](https://github.com/user-attachments/assets/be41778b-d7b9-474a-9e21-3b755825ea37)

**Release version**
Latest Version

**Comment by AmyrAhmady** [comment]
It's auto created when you open server once
