### ISSUE TITLE
GetVehicleLandingGearState result is reverted 

### ISSUE THREAD

**Issue by BeckzyBoi** [openmultiplayer/open.mp#980]
GetVehicleLandingGearState returns 0 for wheels up and 1 for wheels down. It should be the other way around as to match the result of GetPlayerLandingGearState and the definitions from the includes.

This happens with the latest release version 1.3.1.2748 (and all previous releases).

**Comment by AmyrAhmady** [comment]
Fixed in nightly, available officially in next release.
